// Generated by splitting the former monolithic src/index.js.
// Raw data module: constants.js. Re-exported by src/index.js (the barrel).

/**
 * Canonical SSJS (Server-Side JavaScript) catalog for SFMC tooling.
 *
 * Single source of truth consumed by:
 *   - eslint-plugin-sfmc  (globals, unknown-function detection, platform-load checks)
 *   - prettier-plugin-sfmc (language registration)
 *   - vscode-sfmc-language (completions, hover, diagnostics)
 *
 * Schema version: 0.4.0 — additive fields added in this version:
 *   - ampscriptEquivalent?: string | null — the canonical AMPscript function name this
 *       Platform.Function maps to, or null when no AMPscript equivalent exists.
 *       Used by mcp-server-sfmc conversion tools. (PLATFORM_FUNCTIONS only)
 *   - isStatic?: boolean      — true for namespace-level calls (Class.Method()), false for instance calls
 *   - deprecated?: boolean    — true for entries that resolve at runtime but should not be used in new code
 *   - notDefinedAtRuntime?: boolean — true for entries that cannot be USED at runtime in any context
 *       available for testing. Two cases share this flag:
 *         (1) PRIMARY: entries that are officially documented but proven (via live CloudPage test) NOT to
 *             exist in the SSJS engine; calling them throws a ReferenceError (e.g. `Redirect`).
 *         (2) EXTENSION: documented members that the SSJS engine does NOT resolve as documented at
 *             runtime — calling them throws the generic `System.InvalidOperationException:
 *             "Unable to retrieve security descriptor for this frame."`, which in the SFMC SSJS engine
 *             signals an unrecognized member name or an argument count the engine does not accept
 *             (NOT a security or frame restriction). Example: `Platform.Request.GetUserLanguages`, which
 *             throws this error at every arity tried (0/1/2 args), so it cannot be invoked as documented.
 *       The shared EFFECT is identical for both cases: the entry is EXCLUDED from the generated .d.ts so
 *       editors never offer it, flagged by ESLint, but KEPT in ssjs-data (and ssjs.guide) for
 *       discoverability. Pair with officialDocsNote (runtime evidence) and a "use X instead" pointer.
 *   - nonFunctionalAtRuntime?: boolean — the entry EXISTS and RESOLVES at runtime (the namespace/instance
 *       exposes it as a callable), but exhaustive live testing found NO working invocation: every attempted
 *       call fails (returns the string "Error" or throws) and the documented success path could not be
 *       reproduced. Distinct from notDefinedAtRuntime (does NOT exist / cannot be invoked at all → excluded
 *       from .d.ts + completions, flagged as nonexistent) and verificationBlocked (verification could not
 *       even be ATTEMPTED for an environmental reason). Unlike notDefinedAtRuntime, nonFunctionalAtRuntime
 *       entries are KEPT in the .d.ts and completions (they exist); the tooling instead emits a WARNING at
 *       each call site. Requires isConfirmed: true (we confirmed non-function by testing) and pairs with
 *       differsFromOfficialDocs: true plus an officialDocsNote documenting the runtime evidence. NEVER
 *       attribute the failure to permission/access/security — SSJS runs with full server access; state only
 *       the observed return/throw as fact.
 *   - verificationBlocked?: boolean — true when a runtime verification was ATTEMPTED but could not
 *       complete for a concrete technical/environmental reason (missing auth context, absent test
 *       data, or no reproducible working invocation). This is a THIRD state, distinct from both "verified"
 *       (isConfirmed: true) and "never checked" (neither flag set). When true, isConfirmed MUST be
 *       explicitly false and verificationBlockedReason MUST name the blocker category. Put the concrete,
 *       human-readable detail (error codes, SOAP fault names) in officialDocsNote, not the enum value.
 *   - verificationBlockedReason?: string — REQUIRED whenever verificationBlocked is true; one of the
 *       VERIFICATION_BLOCKED_REASONS enum values. Never set on its own.
 *   NOTE: on ssjs.guide BOTH nonFunctionalAtRuntime and verificationBlocked render as the same inline
 *       badge (status="blocked") — the two data states collapse into one visual badge, so these flags
 *       remain the source of truth for which of the two an entry is in.
 *   - isProperty?: boolean    — true for entries accessed without parentheses (e.g. Platform.Request.HasSSL)
 *   - requiresCoreLoad?: boolean — true when the call site requires a preceding Platform.Load("core", "<version>").
 *       RUNTIME NOTE: the bare-name globals injected by Platform.Load (Write, Stringify, Base64Encode,
 *       Base64Decode, Format, Variable, Attribute, …) exist ONLY after Platform.Load("core", …) has run,
 *       so the load must precede any use of them. Once loaded they are usable in that scope and in nested
 *       helper-function bodies that close over it (runtime-verified — closures see them).
 *   - aliasOf?: string        — names the canonical entry this one aliases (dual-call modeling)
 *   - returnEnum?: (string|number|boolean)[] — allowed return literals when returnType is a primitive
 *   - enum?: (string|number|boolean)[]       — allowed literals for a parameter value
 *   - default?: string|number|boolean        — documented default value for a parameter
 *   - optional?: boolean                     — equivalent to Required:No in the docs
 *   - caseInsensitive?: boolean              — true for SOAP-style enums where casing is not enforced
 *   - validArities?: number[] — OPTIONAL, PLATFORM_FUNCTIONS only. Exact set of permitted
 *       argument counts for a DISCONTINUOUS OVERLOAD, where a contiguous minArgs..maxArgs
 *       range would wrongly accept intermediate counts. When present, a call is valid only
 *       when its argument count is within [minArgs, maxArgs] AND a member of this array.
 *       Every entry MUST lie within [minArgs, maxArgs], and both minArgs and maxArgs MUST
 *       be members. Example: HTTPGet accepts exactly 1 or 6 arguments (validArities: [1, 6]);
 *       2-5 arguments throw at runtime. Absent → behavior is a pure contiguous range.
 */

// ── Verification-blocked reasons ─────────────────────────────────────────────
// Fixed enum of concrete technical/environmental reasons why a runtime verification
// was ATTEMPTED but could not complete. Set on an entry as `verificationBlockedReason`
// together with `verificationBlocked: true` and `isConfirmed: false`. The specific
// evidence (error codes, SOAP fault names) belongs in `officialDocsNote`, not here.
//
//   - no-working-invocation  a runtime verification was attempted but no working invocation of
//                         the method was found; document exactly what was tried in officialDocsNote.
//   - needs-auth-context  requires authenticated user / send / subscriber context that
//                         a plain CloudPage test harness cannot provide
//   - no-test-data        requires pre-existing data of a kind not available on the BU
//   - classic-only-no-assets  method only works with classic (legacy) assets and none
//                         exist on the BU to test against
//   - destructive-unsafe  cannot be exercised without unacceptable side effects
//                         (reserved; destructive testing is generally allowed on the QA BU)
export const VERIFICATION_BLOCKED_REASONS = Object.freeze([
    'no-working-invocation',
    'needs-auth-context',
    'no-test-data',
    'classic-only-no-assets',
    'destructive-unsafe',
]);
