// Generated by splitting the former monolithic src/index.js.
// Raw data module: globals.js. Re-exported by src/index.js (the barrel).

// ── Global functions ─────────────────────────────────────────────────────────
// Functions and objects available at the top scope of any SSJS execution context.

export const SSJS_GLOBALS = [
    // ── Native JS globals (not Platform.Function.* aliases) ──────────────────
    {
        name: 'Variable',
        type: 'object',
        aliasOf: 'Platform.Variable', // provenance
        // Standalone bare-name object that DOES work at runtime. Shares the Platform.Variable member set.
        namespaceMethodsOf: 'Platform.Variable',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified (CloudPage GET): bare `Variable` is undefined before `Platform.Load("core", ...)` ' +
            'and an object after it. It shares request-local state with `Platform.Variable`. GetValue preserves ' +
            'string/number/boolean scalars; an explicitly empty value returns `""`; a never-set name returns ' +
            'JavaScript `null` (official docs: string). SetValue returns `undefined` (void-like), while ' +
            '`Platform.Variable.SetValue` returns `null`. The leading `@` is optional.',
        description:
            'Bare-name access to Platform.Variable.* methods (`Variable.SetValue`, `Variable.GetValue`).',
        requiresCoreLoad: true,
    },
    {
        name: 'Request',
        type: 'object',
        // Core Library "Request Object Utility Functions" object. It exposes EXACTLY 6
        // zero-arg METHODS of its own (URL, PagePath, Method, ApplicationID, PackageID,
        // ApplicationBaseURL) — a DIFFERENT, SMALLER member set than Platform.Request
        // (which uses properties like RequestURL and functions like GetCookieValue).
        // The generators resolve its members by this object's OWN name via
        // PLATFORM_NAMESPACE_MAP['Request'] → REQUEST_UTILITY_METHODS (no self-pointer).
        // It must NOT inherit Platform.Request's whole member set.
        isConfirmed: true,
        differsFromOfficialDocs: false,
        officialDocsNote:
            'Runtime-verified (CloudPage GET) per-member: `Request.URL()` returns the full request URL ' +
            'as a string; `Request.Method()` returns the HTTP verb (e.g. `"GET"`); `Request.PagePath()`, ' +
            '`Request.ApplicationID()`, `Request.PackageID()`, and `Request.ApplicationBaseURL()` invoke ' +
            'cleanly and return empty strings (`""`) when read outside their populating context. All 6 ' +
            'members invoke cleanly (a fake member such as `Request.NoSuchMember()` instead throws ' +
            '`Object expected`). This is a smaller, method-based set than `Platform.Request` — do not ' +
            'expect Platform.Request-only members (`RequestURL`, `GetCookieValue`, `GetUserLanguages`) here.',
        description:
            'Core Library "Request Object Utility Functions" object for reading incoming request values. ' +
            'It exposes exactly 6 zero-arg methods: `Request.URL()`, `Request.PagePath()`, `Request.Method()`, ' +
            '`Request.ApplicationID()`, `Request.PackageID()`, and `Request.ApplicationBaseURL()`. Requires ' +
            '`Platform.Load("core","1")`. This is a DISTINCT object from `Platform.Request`, not an alias: ' +
            'it has a smaller, method-only member set and requires Platform.Load, whereas `Platform.Request` ' +
            'works without Platform.Load and mixes properties (e.g. `RequestURL`) with getter methods. ' +
            'For example the current URL is the `Request.URL()` METHOD here versus the `RequestURL` PROPERTY ' +
            'on `Platform.Request`.',
        requiresCoreLoad: true,
    },
    {
        name: 'Recipient',
        type: 'object',
        aliasOf: 'Platform.Recipient',
        isConfirmed: true,
        notDefinedAtRuntime: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): the bare-name global `Recipient` is `undefined` both BEFORE and ' +
            'AFTER Platform.Load("core", ...) — it does NOT exist as a usable alias. Use ' +
            '`Platform.Recipient.GetAttributeValue(...)`, or `Attribute.GetValue(...)` after Platform.Load.',
        description:
            'Documented bare-name alias for Platform.Recipient, but NOT defined at runtime. ' +
            'Use Platform.Recipient.* or Attribute.GetValue() instead.',
    },
    {
        name: 'Attribute',
        type: 'object',
        isConfirmed: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): available as an object after `Platform.Load("core", "1.1.5")` ' +
            '(before load `typeof Attribute` is `undefined`). `Attribute.GetValue(name)` returns a string; ' +
            'in a CloudPage (no subscriber send context) it returns `""` for both real and unknown attribute ' +
            'names, so treat an empty string as "no value in this context" rather than proof the attribute is absent.',
        description:
            'Namespace for reading subscriber attribute values. ' +
            'Call `Attribute.GetValue(name)` to retrieve an attribute for the current recipient.',
        requiresCoreLoad: true,
    },
    {
        name: 'HTTPHeader',
        type: 'object',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): available after Platform.Load("core", ...). `GetValue` reads INBOUND ' +
            'request headers and returns `null` for a header you set via `SetValue` (separate inbound/outbound ' +
            'collections). `Remove` returns `undefined`, not `"OK"`. Official docs claim `host` cannot be ' +
            'changed; `SetValue("Host", …)` does emit an outbound `Host` header. `content-length` remains protected.',
        description:
            'Object that provides access to HTTP request and response headers in SSJS CloudPage context.',
        requiresCoreLoad: true,
    },
    {
        name: 'Platform',
        type: 'object',
        isConfirmed: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): available immediately, with no `Platform.Load` needed. ' +
            'It is a CLR host object (`typeof` reports `clr`), so `for...in` yields no keys and the ' +
            'namespace cannot be enumerated from script — sub-namespaces must be addressed by name. ' +
            '`Platform.Function`, `Platform.Variable`, `Platform.Response`, and `Platform.Request` all resolve.',
        description:
            'Root namespace for SFMC platform APIs including Function, Variable, Response, and Request.',
    },
    {
        name: 'Script',
        type: 'object',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): the bare identifier `Script` is `undefined` — both before and ' +
            'after `Platform.Load("core", ...)` — yet the nested constructors still resolve and work: ' +
            '`Script.Util.WSProxy` and `Script.Util.HttpRequest` are CLR objects and can be instantiated ' +
            'with `new`. The runtime resolves the dotted path without exposing a root object, so the ' +
            'namespace cannot be probed with `typeof Script` or enumerated. Unknown members under the ' +
            'path (for example `Script.Util.Nonexistent`) throw on use rather than returning `undefined`.',
        description:
            'Root namespace for SFMC script utilities. ' +
            'Access sub-namespaces such as `Script.Util` for HTTP request helpers.',
    },
    {
        name: 'String',
        type: 'function',
        minArgs: 0,
        maxArgs: 1,
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified (CloudPage, 2026-08-08): standard JavaScript renders a plain object as "[object Object]", but in the SFMC engine `String({})` THROWS "Object reference not set to an instance of an object." The throw is catchable and does not abort the page. The concatenation form `("" + {})` returns the EMPTY STRING instead of "[object Object]" (same for `[]`). Neither form renders an object — read its fields, or serialize with `Platform.Function.Stringify(value)`. The same throw occurs on .NET-null-backed CLR properties (`resp.contentType`, `resp.encoding`, `resp.headers`), so prefer `("" + value)` for engine values; both forms otherwise produce a real JS string that satisfies `===` and supports string methods.',
        description:
            'Native JavaScript function that converts any value to its string representation. ' +
            'Essential in SSJS for converting the CLR response object returned by Script.Util.HttpRequest.send().content ' +
            'into a JavaScript string that can be passed to Platform.Function.ParseJSON(). ' +
            'Unlike Stringify(), String() works on CLR/.NET objects and does not produce JSON output. ' +
            'Runtime-verified (CloudPage): available with no Platform.Load; `String()` with no argument returns `""`, ' +
            '`String(null)` returns `"null"`. CAVEAT: it does NOT render a plain object — `String({})` throws ' +
            '"Object reference not set to an instance of an object." (catchable) and `("" + {})` yields `""`, ' +
            'not the standard `"[object Object]"`; use `Platform.Function.Stringify(value)` for objects.',
        params: [
            {
                name: 'value',
                description:
                    'Value to convert to string (any type, including CLR objects). A plain object throws — serialize it with Stringify() instead.',
                type: 'any',
            },
        ],
        returnType: 'string',
        syntax: 'String(value)',
        example:
            '// Convert a CLR response object to a JavaScript string for JSON parsing:\n' +
            'var req = new Script.Util.HttpRequest("https://api.example.com/data");\n' +
            'req.method = "GET";\n' +
            'var resp = req.send();\n' +
            'var responseStr = String(resp.content);  // CLR -> JS string\n' +
            'var responseJSON = Platform.Function.ParseJSON(responseStr);\n\n' +
            '// Also works for numbers and other primitives:\n' +
            'var num = 42;\n' +
            'var str = String(num); // "42"',
    },
    {
        name: 'Error',
        type: 'function',
        minArgs: 0,
        maxArgs: 1,
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified: unlike standard JavaScript, a JS-constructed `new Error("msg")` in the SFMC Jint engine does NOT expose the message via `.message` — `err.message` reads back `undefined`, and `Stringify(err)` surfaces only a hidden `{jintException}` (the .NET stack), not the message. Recover the message with `String(err)` or `("" + err)` (both yield the constructor argument), or `err.toString()` (yields "Error: undefined"). This differs from engine-raised errors, which DO carry `.message` + `.description`. Do not rely on `new Error(...).message`.',
        description:
            'Native JavaScript Error constructor. Creates an Error object that can be thrown or caught. ' +
            'Use inside try/catch blocks for structured error handling in SSJS. ' +
            'CAVEAT: for a JS-constructed `new Error("msg")`, the message is NOT readable via `.message` ' +
            '(it returns undefined); use `String(err)` or `("" + err)` to recover it. Engine-raised errors ' +
            '(e.g. from a bad Platform.Function call) instead expose `.message` and `.description`.',
        params: [
            {
                name: 'message',
                description: 'Human-readable description of the error',
                type: 'string',
                optional: true,
            },
        ],
        returnType: 'object',
        syntax: 'new Error([message])',
        example:
            'try {\n' +
            '    var req = new Script.Util.HttpRequest("https://api.example.com/data");\n' +
            '    req.method = "GET";\n' +
            '    req.continueOnError = false;\n' +
            '    var resp = req.send();\n' +
            '    if (resp.statusCode !== 200) {\n' +
            '        throw new Error("Request failed with status: " + resp.statusCode);\n' +
            '    }\n' +
            '} catch (e) {\n' +
            '    // For new Error(...), the message is recovered via String(e), NOT e.message.\n' +
            '    Write("Error: " + String(e));\n' +
            '}',
    },
    {
        name: 'Base64Encode',
        type: 'function',
        minArgs: 1,
        maxArgs: 1,
        requiresCoreLoad: true,
        isConfirmed: true,
        differsFromOfficialDocs: false,
        officialDocsNote:
            'Runtime-verified (CloudPage): the bare-name `Base64Encode` works after `Platform.Load("core", ...)` ' +
            'and returns the encoded string (e.g. Base64Encode("hi") -> "aGk="). This matches the official docs — ' +
            'the Core-library intro documents that these bare-name globals require Platform.Load, so the requirement ' +
            'is documented behavior, not a deviation. SCOPE RULE: bare-name Core globals exist ONLY after ' +
            'Platform.Load has run — call the load first. Once loaded they are usable in that scope and inside ' +
            'nested helper-function bodies that close over it. For charset control or a scope-independent form ' +
            'that needs no Platform.Load, use `Platform.Function.Base64Encode(string[, charset])`.',
        description:
            'Encodes plain text to a Base64 encoded string. ' +
            'For charset control or scope-independent use, use `Platform.Function.Base64Encode(string, charset)` instead.',
        params: [{ name: 'string', description: 'Text to encode', type: 'string' }],
        returnType: 'string',
        syntax: 'Base64Encode(string)',
        example:
            'Platform.Load("core", "1.1.5");\n' +
            'var encoded = Base64Encode(\'Convert to Base64\'); // "Q29udmVydCB0byBCYXNlNjQ="',
    },
    {
        name: 'Base64Decode',
        type: 'function',
        minArgs: 1,
        maxArgs: 1,
        requiresCoreLoad: true,
        isConfirmed: true,
        differsFromOfficialDocs: false,
        officialDocsNote:
            'Runtime-verified (CloudPage): the bare-name `Base64Decode` works after `Platform.Load("core", ...)` ' +
            '(e.g. Base64Decode("aGk=") -> "hi"). This matches the official docs — the Core-library intro documents ' +
            'that these bare-name globals require Platform.Load, so the requirement is documented behavior, not a ' +
            'deviation. SCOPE RULE: bare-name Core globals exist ONLY after Platform.Load has run — call the load ' +
            'first. Once loaded they are usable in that scope and inside nested helper-function bodies that close ' +
            'over it. For charset control or a scope-independent form that needs no Platform.Load, use ' +
            '`Platform.Function.Base64Decode(encodedString[, charset])`.',
        description:
            'Decodes a Base64 encoded string to plain text. ' +
            'For charset control or scope-independent use, use `Platform.Function.Base64Decode(encodedString, charset)` instead.',
        params: [
            {
                name: 'encodedString',
                description: 'Base64 encoded string to decode',
                type: 'string',
            },
        ],
        returnType: 'string',
        syntax: 'Base64Decode(encodedString)',
        example:
            'Platform.Load("core", "1.1.5");\n' +
            'var decoded = Base64Decode(\'VGhpcyB3YXMgYSBCYXNlNjQgZW5jb2RlZCBzdHJpbmcu\'); // "This was a Base64 encoded string."',
    },
    // ── Bare-name aliases for Platform.Function.* (dual-call rule) ───────────
    // Every Platform.Function.X() is also callable as X(). The canonical
    // definition lives in PLATFORM_FUNCTIONS. A subset requires a preceding
    // Platform.Load("core", "1.1.5") call (requiresCoreLoad: true).
    {
        name: 'ContentArea',
        minArgs: 1,
        maxArgs: 4,
        deprecated: true,
        requiresCoreLoad: true,
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): the bare-name `ContentArea` IS defined as a function after ' +
            '`Platform.Load("core", ...)` has run (the load must precede use; once loaded the bare name is ' +
            'usable in that scope and in nested helper bodies that close over it). ' +
            'Only the single-argument form works: passing the id of an existing Content Area returns its ' +
            'content, and a numeric string for the same id works too. Supplying regionName (parameter 2) ' +
            'throws an "invalid parameter value ... ImpressionRegionName ... ResolvedValueParameter" error, ' +
            'which leaves errorMsg and fallbackContent unreachable. An arity-1 call that throws means the id ' +
            'did not resolve to a Content Area. ' +
            'The Platform.Function.ContentArea() variant does not require Platform.Load.',
        description:
            'Retrieves content from a classic Content Area by numeric ID. ' +
            'Salesforce documents Content Areas as deprecated in favour of Content Builder blocks. ' +
            'Note: the Platform.Function.ContentArea() variant does not require Platform.Load and ' +
            'accepts a boolean stopOnError parameter instead of a string errorMsg.',
        params: [
            { name: 'id', description: 'ID of the Content Area.', type: 'string|number' },
            {
                name: 'regionName',
                description: 'Impression region for content.',
                type: 'string',
                optional: true,
            },
            {
                name: 'errorMsg',
                description: 'Error message string returned on failure.',
                type: 'string',
                optional: true,
            },
            {
                name: 'fallbackContent',
                description: 'Default content to display when the area cannot be retrieved.',
                type: 'string',
                optional: true,
            },
        ],
        returnType: 'string',
        returnDescription: 'Rendered content from the Content Area.',
        syntax: 'ContentArea(id[, regionName, errorMsg, fallbackContent])',
        example:
            'Platform.Load("core", "1.1.5");\n' +
            'var content = ContentArea(123456, "impressionRegion", "fallback error msg", "defaultContentHere");',
    },
    {
        name: 'ContentAreaByName',
        minArgs: 1,
        maxArgs: 4,
        deprecated: true,
        requiresCoreLoad: true,
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): the bare-name `ContentAreaByName` IS defined as a function after ' +
            '`Platform.Load("core", ...)` has run (the load must precede use; once loaded the bare name is ' +
            'usable in that scope and in nested helper bodies that close over it). ' +
            'Only the single-argument form works: passing the name of an existing Content Area returns its ' +
            'content. Name matching is case-insensitive and the backslash-separated folder-path form ' +
            'resolves as well, while ' +
            'a CustomerKey, a space-padded name and an unknown name are all rejected. Supplying regionName ' +
            '(parameter 2) throws an "invalid parameter value ... ImpressionRegionName ... ' +
            'ResolvedValueParameter" error, which leaves errorMsg and fallbackContent unreachable. ' +
            'The Platform.Function.ContentAreaByName() variant does not require Platform.Load.',
        description:
            'Retrieves content from a classic Content Area by name. ' +
            'Salesforce documents Content Areas as deprecated in favour of Content Builder blocks. ' +
            'Note: the Platform.Function.ContentAreaByName() variant does not require Platform.Load and ' +
            'accepts a boolean stopOnError parameter instead of a string errorMsg.',
        params: [
            { name: 'name', description: 'Name of the Content Area.', type: 'string' },
            {
                name: 'regionName',
                description: 'Impression region for content.',
                type: 'string',
                optional: true,
            },
            {
                name: 'errorMsg',
                description: 'Error message string returned on failure.',
                type: 'string',
                optional: true,
            },
            {
                name: 'fallbackContent',
                description: 'Default content to display when the area cannot be retrieved.',
                type: 'string',
                optional: true,
            },
        ],
        returnType: 'string',
        returnDescription: 'Rendered content from the Content Area.',
        syntax: 'ContentAreaByName(name[, regionName, errorMsg, fallbackContent])',
        example:
            'Platform.Load("core", "1.1.5");' +
            '\n' +
            String.raw`var content = ContentAreaByName("My Content\\myContentArea", "impressionRegion", "fallback error msg", "defaultContentHere");`,
    },
    {
        name: 'BeginImpressionRegion',
        type: 'function',
        aliasOf: 'Platform.Function.BeginImpressionRegion', // provenance
        minArgs: 1,
        maxArgs: 1,
        requiresCoreLoad: true,
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): the bare-name `BeginImpressionRegion` IS defined as a function after ' +
            '`Platform.Load("core", ...)`, but calling it — with either a string literal or a variable — throws ' +
            '"A BeginImpressionRegion function call includes an invalid parameter value. The values making up the ' +
            'parameter value for this call must be a literal (constant) values." The bare alias and the ' +
            '`Platform.Function.BeginImpressionRegion` form behave identically (both throw the same error), so ' +
            'impression regions are effectively unusable from SSJS — they are an AMPscript-only feature. ' +
            'SCOPE RULE: bare-name Core globals exist ONLY after Platform.Load has run — call the load first.',
        description:
            'Marks the start of a named impression tracking region within content. ' +
            'Runtime note: unusable from SSJS — every call (literal or variable argument) throws a ' +
            'resolved-value error; impression regions are an AMPscript-only feature.',
        params: [{ name: 'name', description: 'The impression region name.', type: 'string' }],
        returnType: 'void',
        syntax: 'BeginImpressionRegion(name)',
        example:
            'Platform.Load("core", "1.1.5");\n' +
            '// Note: throws at runtime in SSJS — impression regions are AMPscript-only.\n' +
            'BeginImpressionRegion("hero-banner");',
    },
    {
        name: 'EndImpressionRegion',
        type: 'function',
        aliasOf: 'Platform.Function.EndImpressionRegion', // provenance
        minArgs: 0,
        maxArgs: 1,
        requiresCoreLoad: true,
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): the bare-name `EndImpressionRegion` IS defined as a function after ' +
            '`Platform.Load("core", ...)` and can be called without throwing. It DIFFERS from its ' +
            '`Platform.Function.EndImpressionRegion` counterpart in return value: the bare alias returns ' +
            '`undefined` (typeof "undefined"), whereas `Platform.Function.EndImpressionRegion()` returns a genuine ' +
            '`null` (typeof "object", === null). The official docs type the return as void. Because ' +
            '`BeginImpressionRegion` is unusable from SSJS, this method has no practical effect in SSJS either. ' +
            'SCOPE RULE: bare-name Core globals exist ONLY after Platform.Load has run — call the load first.',
        description:
            'Marks the end of an impression tracking region within content. ' +
            'Runtime note: the bare alias returns `undefined` (its `Platform.Function.EndImpressionRegion` ' +
            'counterpart returns `null`); has no practical effect in SSJS because impression regions are ' +
            'AMPscript-only.',
        params: [
            {
                name: 'closeAll',
                description: 'Optional flag to close all open impression regions.',
                type: 'string|boolean|number',
                optional: true,
            },
        ],
        returnType: 'undefined',
        syntax: 'EndImpressionRegion([closeAll])',
        example:
            'Platform.Load("core", "1.1.5");\n' +
            'EndImpressionRegion(); // returns undefined (Platform.Function form returns null)',
    },
    {
        name: 'Now',
        type: 'function',
        aliasOf: 'Platform.Function.Now', // provenance
        minArgs: 0,
        maxArgs: 1,
        requiresCoreLoad: true,
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): the bare-name `Now` works after `Platform.Load("core", ...)` and ' +
            'returns the same kind of value as `Platform.Function.Now()` — a genuine Date object: typeof "object", ' +
            '`Object.prototype.toString` reports "[object Date]", `.constructor === Date`, and ' +
            '`getFullYear()`/`getHours()`/`getTime()` all work (identical to `new Date()`). The only anomaly is that ' +
            '`instanceof Date` returns false, due to the engine-wide `instanceof`-on-builtins bug — detect via ' +
            '`.constructor === Date`, not `instanceof`. It coerces to an RFC 2822-style string such as ' +
            '"Tue, 21 Jul 2026 10:18:24 GMT-06:00" during output. The official docs describe the return as an ' +
            'RFC 2822-compliant date-time string. Surplus arguments beyond maxArgs 1 are silently ignored on the ' +
            'bare form; `Platform.Function.Now(...)` throws on arity 2+. useContextTime also accepts number 0/1 and ' +
            'the strings "true"/"false". ' +
            'SCOPE RULE: bare-name Core globals exist ONLY after Platform.Load has run — call the load first.',
        description:
            'Returns the current server date/time as a Date object (in the account timezone, Central by ' +
            'default), or the timestamp of the triggering send when called with `true`. Same return shape as ' +
            '`Platform.Function.Now()`; surplus arguments are ignored (the qualified form throws on arity 2+).',
        params: [
            {
                name: 'useContextTime',
                description:
                    'Pass `true` to return the timestamp of the triggering send instead of the current time. Also accepts number 0/1 and the strings "true"/"false".',
                type: 'string|boolean|number',
                optional: true,
            },
        ],
        returnType: 'Date',
        syntax: 'Now([useContextTime])',
        example:
            'Platform.Load("core", "1.1.5");\n' +
            'var current = Now(); // e.g. "Tue, 21 Jul 2026 10:18:24 GMT-06:00"\n' +
            'Write(current.getFullYear()); // 2026',
    },
    {
        name: 'DateTime.SystemDateToLocalDate',
        type: 'function',
        aliasOf: 'Platform.Function.SystemDateToLocalDate', // provenance
        minArgs: 1,
        maxArgs: 1,
        requiresCoreLoad: true,
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): `DateTime.SystemDateToLocalDate` works after `Platform.Load("core", ...)` ' +
            'and returns the same value as `Platform.Function.SystemDateToLocalDate()` — a genuine Date object: ' +
            'typeof "object", `Object.prototype.toString` reports "[object Date]", `.constructor === Date`, and ' +
            '`getFullYear()`/`getHours()`/`getTime()` all work (identical to `new Date()`). The only anomaly is that ' +
            '`instanceof Date` returns false, due to the engine-wide `instanceof`-on-builtins bug — detect via ' +
            '`.constructor === Date`, not `instanceof`. It coerces to an ISO-like string when written or stringified. ' +
            'The official docs type the return value as a string. SCOPE RULE: bare-name Core globals exist ONLY after ' +
            'Platform.Load has run — call the load first.',
        description:
            'Converts a date-time value from Marketing Cloud system time (CST, without daylight saving) to the ' +
            'local time of the account or user. Returns a Date object. Behaves identically to ' +
            '`Platform.Function.SystemDateToLocalDate()`.',
        params: [
            {
                name: 'dateString',
                description: 'The system-time date-time value to convert.',
                type: 'string',
            },
        ],
        returnType: 'Date',
        syntax: 'DateTime.SystemDateToLocalDate(dateString)',
        example:
            'Platform.Load("core", "1.1.5");\n' +
            'var localDate = DateTime.SystemDateToLocalDate(Now());\n' +
            'Write(localDate);',
    },
    {
        name: 'DateTime.LocalDateToSystemDate',
        type: 'function',
        aliasOf: 'Platform.Function.LocalDateToSystemDate', // provenance
        minArgs: 1,
        maxArgs: 1,
        requiresCoreLoad: true,
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): `DateTime.LocalDateToSystemDate` works after `Platform.Load("core", ...)` ' +
            'and returns the same value as `Platform.Function.LocalDateToSystemDate()` — a genuine Date object: ' +
            'typeof "object", `Object.prototype.toString` reports "[object Date]", `.constructor === Date`, and ' +
            '`getFullYear()`/`getHours()`/`getTime()` all work (identical to `new Date()`). The only anomaly is that ' +
            '`instanceof Date` returns false, due to the engine-wide `instanceof`-on-builtins bug — detect via ' +
            '`.constructor === Date`, not `instanceof`. It coerces to an ISO-like string when written or stringified. ' +
            'The official docs type the return value as a string. SCOPE RULE: bare-name Core globals exist ONLY after ' +
            'Platform.Load has run — call the load first.',
        description:
            'Converts a date-time value from the local time of the account or user to Marketing Cloud system time ' +
            '(CST, without daylight saving). Returns a Date object. Behaves identically to ' +
            '`Platform.Function.LocalDateToSystemDate()`.',
        params: [
            {
                name: 'dateString',
                description: 'The local-time date-time value to convert.',
                type: 'string',
            },
        ],
        returnType: 'Date',
        syntax: 'DateTime.LocalDateToSystemDate(dateString)',
        example:
            'Platform.Load("core", "1.1.5");\n' +
            'var systemDate = DateTime.LocalDateToSystemDate("8/5/2025 12:00:00 PM");\n' +
            'Write(systemDate);',
    },
    {
        name: 'Redirect',
        type: 'function',
        requiresCoreLoad: true,
        minArgs: 2,
        maxArgs: 2,
        isConfirmed: true,
        differsFromOfficialDocs: false,
        officialDocsNote:
            'Runtime-verified (CloudPage): the bare-name `Redirect` IS defined as a function after ' +
            '`Platform.Load("core", ...)` and actually performs the redirect. This matches the official docs — ' +
            'the Core-library intro documents that these bare-name globals require Platform.Load, so the requirement ' +
            'is documented behavior, not a deviation. SCOPE RULE: bare-name Core globals exist ONLY after ' +
            'Platform.Load has run — call the load first. Once loaded they are usable in that scope and inside ' +
            'nested helper-function bodies that close over it. For a scope-independent form that needs no ' +
            'Platform.Load, use `Platform.Response.Redirect(url, movedPermanently)`. ' +
            'Meaningful only in CloudPage context.',
        description:
            'Redirects the browser to another address. ' +
            'For scope-independent use that needs no Platform.Load, use `Platform.Response.Redirect(url, movedPermanently)`. ' +
            'Meaningful only in CloudPage context.',
        params: [
            {
                name: 'url',
                description: 'The address to send the browser to.',
                type: 'string',
            },
            {
                name: 'movedPermanently',
                description:
                    'Pass `true` / `1` / `"true"` for an HTTP 301 (permanent) redirect or `false` / `0` / `"false"` for a 302 (temporary) redirect.',
                type: 'string|boolean|number',
            },
        ],
        returnType: 'void',
        syntax: 'Redirect(url, movedPermanently)',
        example:
            'Platform.Load("core", "1.1.5");\n' +
            'Redirect("https://www.example.com", false); // or, scope-independent: Platform.Response.Redirect("https://www.example.com", false);',
    },
    {
        name: 'GUID',
        type: 'function',
        aliasOf: 'Platform.Function.GUID', // provenance
        minArgs: 0,
        maxArgs: 0,
        requiresCoreLoad: true,
        isConfirmed: true,
        differsFromOfficialDocs: false,
        officialDocsNote:
            'Runtime-verified (CloudPage): the bare-name `GUID` works after `Platform.Load("core", ...)` and ' +
            'returns a lowercase canonical UUID v4 string of 36 characters (same shape as ' +
            '`Platform.Function.GUID()`). Surplus arguments are silently ignored on the bare form; ' +
            '`Platform.Function.GUID(...)` throws if any argument is passed. SCOPE RULE: bare-name Core ' +
            'globals exist ONLY after Platform.Load has run — call the load first.',
        description:
            'Generates a new globally unique identifier as a lowercase canonical UUID v4 string (36 characters). ' +
            'Requires Platform.Load("core"). Same return shape as Platform.Function.GUID(); surplus arguments ' +
            'are ignored (the qualified form throws).',
        params: [],
        returnType: 'string',
        syntax: 'GUID()',
        example:
            'Platform.Load("core", "1.1.5");\n' +
            'var id = GUID(); // e.g. "f038aa14-708f-4392-a329-7dfa46abaf4b"',
    },
    {
        name: 'IsEmailAddress',
        type: 'function',
        aliasOf: 'Platform.Function.IsEmailAddress', // provenance
        minArgs: 1,
        maxArgs: 1,
        requiresCoreLoad: true,
        isConfirmed: true,
        differsFromOfficialDocs: false,
        officialDocsNote:
            'Runtime-verified (CloudPage): the bare-name `IsEmailAddress` works after `Platform.Load("core", ...)` ' +
            'and returns the same boolean as `Platform.Function.IsEmailAddress()` for the documented 1-argument ' +
            'form (e.g. "a@b.com" -> true, "nope" -> false). Calling with no arguments returns false (does not ' +
            'throw); surplus arguments are silently ignored. `Platform.Function.IsEmailAddress` throws on arity 0 ' +
            'and on surplus arguments. Documented contract remains minArgs/maxArgs 1. SCOPE RULE: bare-name Core ' +
            'globals exist ONLY after Platform.Load has run — call the load first.',
        description:
            'Checks whether a string is a valid email address format. Same boolean answers as ' +
            '`Platform.Function.IsEmailAddress()` for one string argument; arity 0 returns false and surplus ' +
            'arguments are ignored (the qualified form throws).',
        params: [{ name: 'value', description: 'The string to validate.', type: 'string' }],
        returnType: 'boolean',
        syntax: 'IsEmailAddress(value)',
        example:
            'Platform.Load("core", "1.1.5");\n' +
            'if (IsEmailAddress(emailInput)) { Write("Valid email"); }',
    },
    {
        name: 'IsPhoneNumber',
        type: 'function',
        aliasOf: 'Platform.Function.IsPhoneNumber', // provenance
        minArgs: 1,
        maxArgs: 1,
        requiresCoreLoad: true,
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): the bare-name `IsPhoneNumber` works after `Platform.Load("core", ...)` ' +
            'and returns the same boolean as `Platform.Function.IsPhoneNumber()` for the documented 1-argument form. ' +
            'Calling with no arguments returns false (does not throw); surplus arguments are silently ignored. ' +
            '`Platform.Function.IsPhoneNumber` throws on arity 0 and on surplus arguments. Documented contract ' +
            'remains minArgs/maxArgs 1. The official docs describe generic "valid phone number" validation; see the ' +
            '`Platform.Function.IsPhoneNumber` entry for the NANP runtime format details. SCOPE RULE: bare-name ' +
            'Core globals exist ONLY after Platform.Load has run — call the load first.',
        description:
            'Checks whether a value is a valid North American Numbering Plan (NANP) phone number. Same boolean ' +
            'answers as `Platform.Function.IsPhoneNumber()` for one argument; arity 0 returns false and surplus ' +
            'arguments are ignored (the qualified form throws). See that entry for the NANP format details.',
        params: [{ name: 'value', description: 'The value to validate.', type: 'string|number' }],
        returnType: 'boolean',
        syntax: 'IsPhoneNumber(value)',
        example:
            'Platform.Load("core", "1.1.5");\n' +
            'if (IsPhoneNumber(phoneInput)) { Write("Valid phone"); }',
    },
    {
        name: 'Write',
        type: 'function',
        aliasOf: 'Platform.Response.Write', // provenance
        minArgs: 1,
        maxArgs: 1,
        requiresCoreLoad: true,
        isConfirmed: true,
        differsFromOfficialDocs: false,
        officialDocsNote:
            'Runtime-verified (CloudPage): the bare-name `Write` works after `Platform.Load("core", ...)` and ' +
            'appends to the response (no automatic newline; returns undefined). Platform.Load is required for the ' +
            'bare name (documented Core-library intro behaviour, not a deviation). Zero arguments and surplus ' +
            'arguments are soft (no throw; surplus ignored) while the documented contract remains one required ' +
            'string. Non-string values use CLR stringification — objects/arrays emit host type names, booleans ' +
            'emit `True`/`False` — not JavaScript `toString()` / `[object Object]`. Prefer `Stringify` for objects. ' +
            'For a scope-independent form that needs no Platform.Load, use `Platform.Response.Write(text)` ' +
            '(returns null).',
        description:
            'Writes text to the HTTP response output. Non-string values use CLR stringification ' +
            '(not JS toString); use Stringify for objects. ' +
            'For scope-independent output that needs no Platform.Load, use `Platform.Response.Write(text)` instead.',
        params: [{ name: 'text', description: 'Text to write to the response.', type: 'string' }],
        returnType: 'void',
        syntax: 'Write(text)',
        example:
            'Platform.Load("core", "1.1.5");\n' +
            'Write("Hello world"); // or, scope-independent: Platform.Response.Write("Hello world");',
    },
    {
        name: 'Stringify',
        type: 'function',
        aliasOf: 'Platform.Function.Stringify', // provenance
        minArgs: 1,
        maxArgs: 1,
        requiresCoreLoad: true,
        isConfirmed: true,
        differsFromOfficialDocs: false,
        officialDocsNote:
            'Runtime-verified (CloudPage): the bare-name `Stringify` works after `Platform.Load("core", ...)` ' +
            '(e.g. Stringify({a:1,b:"x"}) -> \'{"a":1,"b":"x"}\'). Surplus arguments are silently ignored and ' +
            'zero arguments return the string "null"; `Platform.Function.Stringify(...)` throws on wrong arity. ' +
            'This matches the official docs — the Core-library intro documents that these bare-name globals ' +
            'require Platform.Load, so the requirement is documented behavior, not a deviation. SCOPE RULE: ' +
            'bare-name Core globals exist ONLY after Platform.Load has run — call the load first. Once loaded ' +
            'they are usable in that scope and inside nested helper-function bodies that close over it. For a ' +
            'scope-independent form that needs no Platform.Load, use `Platform.Function.Stringify(value)`.',
        description:
            'Serializes a value to a JSON string. Requires Platform.Load("core"). Same JSON text as ' +
            '`Platform.Function.Stringify(value)` for a given value; surplus arguments are ignored and zero ' +
            'arguments return "null" (the qualified form throws). For scope-independent use, prefer ' +
            '`Platform.Function.Stringify(value)`.',
        params: [{ name: 'value', description: 'Value to serialize to JSON.', type: 'any' }],
        returnType: 'string',
        syntax: 'Stringify(value)',
        example:
            'Platform.Load("core", "1.1.5");\n' +
            'var json = Stringify({ a: 1, b: "x" }); // \'{"a":1,"b":"x"}\'',
    },
    // ── Core-library namespace markers ───────────────────────────────────────
    {
        name: 'DateTime',
        type: 'object',
        isConfirmed: true,
        officialDocsNote:
            'Runtime-verified (CloudPage, Platform.Load("core","1.1.5")): available. ' +
            '`SystemDateToLocalDate` / `LocalDateToSystemDate` return genuine Date objects (typeof "object", ' +
            '`Object.prototype.toString` === "[object Date]", `.constructor === Date`, working `getFullYear()` etc.; ' +
            'only `instanceof Date` is false due to the engine-wide instanceof-on-builtins bug), which also coerce ' +
            'transparently to strings via `"" + value`, `String(value)`, or `Write(value)`. ' +
            '`DateTime.TimeZone.Retrieve(filter)` returns rows carrying `ID` (number) and `Name` (string) ' +
            'that `Stringify()` serializes normally.',
        description:
            'Namespace for time zone and date utilities. ' +
            'Access sub-namespaces such as `DateTime.TimeZone` for time zone operations.',
        requiresCoreLoad: true,
    },
    {
        name: 'ErrorUtil',
        type: 'object',
        deprecated: true,
        maxCoreVersion: '1',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): `ErrorUtil` is provided ONLY by `Platform.Load("Core", "1")`. ' +
            'Under newer Core versions ("1.1.1", "1.1.5", …) it is `undefined`. Effectively deprecated in Core > 1. ' +
            'Prefer checking `result.Status` and throwing `new Error(...)` instead of ErrorUtil.ThrowWSProxyError.',
        description:
            'Utility namespace for WSProxy error handling. ' +
            'Call `ErrorUtil.ThrowWSProxyError(result)` to convert WSProxy error-status results into thrown exceptions. ' +
            'DEPRECATED: only available under `Platform.Load("Core", "1")`; unavailable in newer Core versions.',
        requiresCoreLoad: true,
    },
    {
        name: 'Format',
        type: 'function',
        minArgs: 2,
        maxArgs: 2,
        requiresCoreLoad: true,
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): bare-name `Format` requires `Platform.Load("core", ...)`. ' +
            'Numeric codes match the official examples (e.g. Format(4213.65, "C2") -> "$4,213.65"). ' +
            'DIFFERS: predefined short-form `d` returns a four-digit year (`8/5/2024` for the sample ' +
            'instant), not the two-digit year (`8/5/24`) shown in the official docs. ' +
            'textToFormat also accepts a real Date for date format codes (same result as the matching ' +
            'date string). Boolean is rejected for numeric codes. SCOPE RULE: bare-name Core globals ' +
            'exist ONLY after Platform.Load has run.',
        description:
            'Applies a formatting rule to a string, number, or Date. ' +
            'Use format codes such as `C` (currency), `D` (decimal), `N` (number with separators), ' +
            '`P` (percentage), `O` (ISO 8601 date), `s` (sortable date), `d` (short date), `t` (12-hour time), etc. ' +
            'Append a digit to control decimal places, e.g. `C2` for two decimal places.',
        params: [
            {
                name: 'textToFormat',
                description: 'The string, number, or Date to apply a formatting rule to.',
                type: 'string|number|Date',
            },
            {
                name: 'formatCode',
                description:
                    'A format code to apply. Numeric: C, D, E, F, G, N, P (append digit for decimal places). ' +
                    'Date/time: d, M, f, g, O, r, s, t, T, or a custom pattern.',
                type: 'string',
            },
        ],
        returnType: 'string',
        syntax: 'Format(textToFormat, formatCode)',
        example:
            'Platform.Load("core", "1.1.5");\n' +
            'var price = Format(4213.65, "C2");  // "$4,213.65"\n' +
            'var isoDate = Format("2024-08-05T13:41:23", "O");  // "2024-08-05T13:41:23.0000000"\n' +
            'Write(price + " / " + isoDate);',
    },
];
