// Generated by splitting the former monolithic src/index.js.
// Raw data module: http-wsproxy.js. Re-exported by src/index.js (the barrel).

// ── HTTP object methods ──────────────────────────────────────────────────────

/**
 * @type {{name: string, minArgs: number, maxArgs: number, description: string, params?: {name: string, description: string, type?: string, optional?: boolean}[], returnType?: string, syntax?: string}[]}
 */
export const HTTP_METHODS = [
    {
        name: 'Get',
        minArgs: 1,
        maxArgs: 3,
        requiresCoreLoad: true,
        isConfirmed: true,
        description:
            'Performs an HTTP GET request and returns the response body. ' +
            'When supplying `headerNames` and `headerValues`, both arrays must have equal length and parallel ordering.',
        params: [
            { name: 'url', description: 'URL to request.', type: 'string' },
            {
                name: 'headerNames',
                description: 'Array of header names (co-required with headerValues).',
                type: 'array',
                optional: true,
            },
            {
                name: 'headerValues',
                description: 'Array of header values, one per entry in headerNames (co-required).',
                type: 'array',
                optional: true,
            },
        ],
        returnType: '{ Status: number, Content: string }',
        syntax: 'HTTP.Get(url[, headerNames, headerValues])',
        example:
            'Platform.Load("core", "1.1.5");\n' +
            'var body = HTTP.Get("https://api.example.com/data");\n' +
            'var obj = Platform.Function.ParseJSON(String(body));',
    },
    {
        name: 'Post',
        minArgs: 3,
        maxArgs: 5,
        requiresCoreLoad: true,
        isConfirmed: true,
        description:
            'Performs an HTTP POST request with a content type and payload. ' +
            'Returns an object whose `StatusCode` is a number and whose `Response` is an array-like whose first element (`Response[0]`) is the response body string. ' +
            'Custom headers are optional; when supplied, `headerNames` and `headerValues` must be paired (equal length) — passing only one of the two throws a mismatch error.',
        params: [
            { name: 'url', description: 'URL to post to.', type: 'string' },
            { name: 'contentType', description: 'MIME type of the request body.', type: 'string' },
            { name: 'payload', description: 'Request body content.', type: 'string' },
            {
                name: 'headerNames',
                description:
                    'Array of header names to include in the request (co-required with headerValues).',
                type: 'string[]',
                optional: true,
            },
            {
                name: 'headerValues',
                description: 'Array of header values, one per entry in headerNames (co-required).',
                type: 'array',
                optional: true,
            },
        ],
        returnType: '{ StatusCode: number, Response: string[] }',
        syntax: 'HTTP.Post(url, contentType, payload[, headerNames, headerValues])',
        example:
            'Platform.Load("core", "1.1.5");\n' +
            'var payload = Stringify({ email: "jane@example.com" });\n' +
            'var response = HTTP.Post("https://api.example.com/items", "application/json", payload);\n' +
            'if (response.StatusCode == 200) { var body = response.Response[0]; }',
    },
];

// ── WSProxy methods ──────────────────────────────────────────────────────────

/**
 * @type {{name: string, minArgs: number, maxArgs: number, description: string, params?: {name: string, description: string, type?: string, optional?: boolean}[], returnType?: string, syntax?: string}[]}
 */
export const WSPROXY_METHODS = [
    {
        name: 'createItem',
        isStatic: false,
        minArgs: 2,
        maxArgs: 3,
        isConfirmed: true,
        description:
            'Creates a new Marketing Cloud object via the SOAP API. Collection properties must be flat arrays: a DataExtension takes Fields: [...] and a DataExtensionObject takes Properties: [{ Name, Value }]. The nested SOAP wrappers Fields: { Field: [...] } and Properties: { Property: [...] } throw "Error executing create call.", and createItem does not accept the bracketed DataExtensionObject[key] object type — name the data extension through CustomerKey instead. It never upserts: an existing primary key returns Status "Error" and leaves the stored row unchanged.',
        params: [
            { name: 'objectType', description: 'SOAP API object type name', type: 'string' },
            { name: 'properties', description: 'Object properties to set', type: 'object' },
            {
                name: 'createOptions',
                description:
                    'Optional SOAP CreateOptions object (e.g. RequestType, QueuePriority).',
                type: 'object',
                optional: true,
            },
        ],
        returnType: 'WSProxyResult',
        returnDescription:
            'Object with Status ("OK" or "Error"), RequestID, and a Results array holding one per-item result with StatusCode, StatusMessage and Object.',
        syntax: '<WSProxyInstance>.createItem(objectType, properties[, createOptions])',
        example:
            'var api = new Script.Util.WSProxy();\n' +
            'var result = api.createItem("DataExtensionObject", {\n' +
            '    CustomerKey: "MyDE_Key",\n' +
            '    Properties: [{ Name: "Email", Value: "jane@example.com" }]\n' +
            '});\n' +
            'if (result.Status === "OK") { Write("Created"); }',
    },
    {
        name: 'updateItem',
        isStatic: false,
        minArgs: 2,
        maxArgs: 3,
        isConfirmed: true,
        description: 'Updates a single existing Marketing Cloud object via the SOAP API.',
        params: [
            { name: 'objectType', description: 'SOAP API object type name', type: 'string' },
            { name: 'properties', description: 'Object properties to update', type: 'object' },
            {
                name: 'updateOptions',
                description: 'Optional SOAP UpdateOptions object (e.g. { SaveOptions: [...] })',
                type: 'object',
                optional: true,
            },
        ],
        returnType: 'WSProxyResult',
        returnDescription:
            'Object with Status, RequestID, and a single-entry Results array. The one Results entry carries StatusCode, StatusMessage, OrdinalID, ErrorCode, and an Object wrapper.',
        syntax: '<WSProxyInstance>.updateItem(objectType, properties[, updateOptions])',
        example:
            'var api = new Script.Util.WSProxy();\n' +
            'var result = api.updateItem("DataExtensionObject", {\n' +
            '    CustomerKey: "MyDE",\n' +
            '    Keys: [{ Name: "Email", Value: "a@example.com" }],\n' +
            '    Properties: [{ Name: "Status", Value: "inactive" }]\n' +
            '});\n' +
            'if (result.Status === "OK") { Write("Updated"); }',
    },
    {
        name: 'deleteItem',
        isStatic: false,
        minArgs: 2,
        maxArgs: 3,
        isConfirmed: true,
        description: 'Deletes a Marketing Cloud object via the SOAP API.',
        params: [
            { name: 'objectType', description: 'SOAP API object type name', type: 'string' },
            {
                name: 'properties',
                description:
                    'Object properties identifying the item to delete. For a DataExtensionObject row use a CustomerKey property plus a FLAT Keys array of { Name, Value } pairs — the nested Keys: { Key: [...] } form and the bracketed objectType "DataExtensionObject[key]" both throw.',
                type: 'object',
            },
            {
                name: 'deleteOptions',
                description:
                    'Optional SOAP DeleteOptions object (e.g. RequestType, QueuePriority).',
                type: 'object',
                optional: true,
            },
        ],
        returnType: 'WSProxyResult',
        returnDescription:
            'Object with Status, RequestID, and a Results array of per-item results (StatusCode, StatusMessage, ErrorCode). The top-level object has no StatusMessage.',
        syntax: '<WSProxyInstance>.deleteItem(objectType, properties[, deleteOptions])',
        example:
            'var api = new Script.Util.WSProxy();\n' +
            'var result = api.deleteItem("DataExtensionObject", {\n' +
            '    CustomerKey: "MyDE",\n' +
            '    Keys: [{ Name: "Email", Value: "jane@example.com" }]\n' +
            '});\n' +
            'if (result.Status === "OK") { Write("Deleted"); }',
    },
    {
        name: 'retrieve',
        isStatic: false,
        minArgs: 2,
        maxArgs: 5,
        description:
            'Retrieves Marketing Cloud objects matching an optional filter via the SOAP API. The third parameter is a simple or complex filter; the fourth sets RetrieveOptions; the fifth sets additional request properties such as QueryAllAccounts.',
        params: [
            { name: 'objectType', description: 'SOAP API object type name', type: 'string' },
            { name: 'columns', description: 'Array of property names to retrieve', type: 'array' },
            {
                name: 'filter',
                description: 'Simple or complex filter object',
                type: 'object',
                optional: true,
            },
            {
                name: 'retrieveOptions',
                description:
                    'Properties to set on the SOAP RetrieveOptions object. Set BatchSize (1..2500) here to force paged results; a value above 2500 is ignored and the default page size applies.',
                type: 'object',
                optional: true,
            },
            {
                name: 'requestProps',
                description:
                    'Additional request properties, e.g. QueryAllAccounts (boolean) and ContinueRequest (a RequestID string). Setting ContinueRequest to the RequestID from a prior paged retrieve fetches the next page — a retrieve-based alternative to getNextBatch.',
                type: 'object',
                optional: true,
            },
        ],
        returnType: 'WSProxyResult',
        returnDescription:
            'Object with Status, HasMoreRows, RequestID, and Results array. When a result set is paged, Status is "MoreDataAvailable" and HasMoreRows is true; the final page returns Status "OK" and HasMoreRows false.',
        syntax: '<WSProxyInstance>.retrieve(objectType, columns[, filter[, retrieveOptions[, requestProps]]])',
        officialDocsNote:
            'Runtime verified on a CloudPage: retrieve(objectType, columns, null, { BatchSize: 2 }, { QueryAllAccounts: false }) against a 6-row Data Extension returned a first page with Status "MoreDataAvailable", HasMoreRows true, a RequestID, and exactly 2 rows — the retrieveOptions.BatchSize argument pages cleanly without throwing. Continuation via the requestProps.ContinueRequest field works: setting props.ContinueRequest to the returned RequestID and calling retrieve again returned each subsequent page (3 pages of 2 rows, 6 total), with the RequestID held constant across the sequence and HasMoreRows flipping to false (Status "OK") on the final page. This is a retrieve-only paging alternative to getNextBatch. BatchSize caps at 2500; larger values are ignored.',
        example:
            'var api = new Script.Util.WSProxy();\n' +
            'var cols = ["Name", "CustomerKey", "Status"];\n' +
            'var filter = {\n' +
            '    Property: "Status",\n' +
            '    SimpleOperator: "equals",\n' +
            '    Value: "Active"\n' +
            '};\n' +
            'var result = api.retrieve("DataExtension", cols, filter);\n' +
            'if (result.Status === "OK") {\n' +
            '    var rows = result.Results;\n' +
            '    for (var i = 0; i < rows.length; i++) {\n' +
            '        Write(rows[i].Name + "<br>");\n' +
            '    }\n' +
            '}',
        isConfirmed: true,
    },
    {
        name: 'getNextBatch',
        isStatic: false,
        minArgs: 2,
        maxArgs: 2,
        description:
            'Retrieves the next page of results from a previous retrieve call that returned HasMoreRows = true.',
        params: [
            {
                name: 'objectType',
                description: 'SOAP API object type name used in the original retrieve call',
                type: 'string',
            },
            {
                name: 'requestId',
                description: 'RequestID returned by the previous retrieve response',
                type: 'string',
            },
        ],
        returnType: 'WSProxyResult',
        returnDescription: 'Object with Status, HasMoreRows, RequestID, and Results array.',
        syntax: '<WSProxyInstance>.getNextBatch(objectType, requestId)',
        example:
            'var api = new Script.Util.WSProxy();\n' +
            'var result = api.retrieve("DataExtension", ["Name"], {});\n' +
            'while (result.HasMoreRows) {\n' +
            '    result = api.getNextBatch("DataExtension", result.RequestID);\n' +
            '    for (var i = 0; i < result.Results.length; i++) {\n' +
            '        Write(result.Results[i].Name + "<br>");\n' +
            '    }\n' +
            '}',
        isConfirmed: true,
        officialDocsNote:
            'Runtime (CloudPage) proved the full paginated continuation: a natural retrieve of a Data Extension seeded with 2600 rows returned the first page with Status "MoreDataAvailable", HasMoreRows true, a RequestID, and exactly 2500 rows (the default page size); passing that objectType + RequestID to getNextBatch returned the next page with Status "OK", HasMoreRows false, and the remaining 100 rows, for a total of 2600 across two pages. Each Results row exposes a Properties array of { Name, Value } pairs. Pagination therefore happens naturally once a result set exceeds the 2500-row default page size. Calling getNextBatch with a completed/invalid RequestID returns Status "Error: The RequestID sent through ContinueRequest does not exist." The call maps to the SOAP ContinueRequest operation.',
    },
    {
        name: 'performItem',
        isStatic: false,
        minArgs: 3,
        maxArgs: 4,
        description: 'Executes a perform action on a single Marketing Cloud object.',
        params: [
            { name: 'objectType', description: 'SOAP API object type name.', type: 'string' },
            {
                name: 'properties',
                description:
                    'Object properties identifying the target item (e.g. { ObjectID: "..." }).',
                type: 'object',
            },
            {
                name: 'action',
                description:
                    'Action to perform, typically "Start". The verb is case-insensitive at runtime ("start" works identically to "Start").',
                type: 'string',
                enum: ['Start'],
            },
            {
                name: 'performOptions',
                description: 'Properties of the SOAP PerformOptions object.',
                type: 'object',
                optional: true,
            },
        ],
        returnType: 'WSProxyResult',
        returnDescription:
            'Object with Status (string, "OK" on success), StatusMessage (string, empty on success), RequestID (string) and Results (Array with a single entry for the acted-on item). The Results[0] element carries StatusCode, StatusMessage ("QueryDefinition perform called successfully"), OrdinalID, ErrorCode plus an Object (the acted-on API object) and a Task sub-object (StatusCode, StatusMessage, ID, TblAsyncID, InteractionObjectID).',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime (CloudPage) confirmed the (objectType, properties, action[, performOptions]) signature and the WSProxyResult return shape: Status/StatusMessage/RequestID plus a single-entry Results array. Against a freshly-created active QueryDefinition, both "Start" and lowercase "start" returned Status "OK" with Results[0].StatusMessage "QueryDefinition perform called successfully" — the action verb is case-insensitive, so the docs\' Enum(\'Start\') is not case-sensitive as the page previously claimed. The Results[0] element exposes StatusCode, StatusMessage, OrdinalID, ErrorCode, an Object wrapper and a Task sub-object (with InteractionObjectID); the official docs do not detail this per-item structure.',
        syntax: '<WSProxyInstance>.performItem(objectType, properties, action[, performOptions])',
        example:
            'var api = new Script.Util.WSProxy();\n' +
            'var result = api.performItem("QueryDefinition", { ObjectID: queryObjectId }, "Start");\n' +
            'Write(result.Status);',
    },
    {
        name: 'performBatch',
        isStatic: false,
        minArgs: 3,
        maxArgs: 4,
        description:
            'Executes a perform action on multiple Marketing Cloud objects in a single SOAP API call.',
        params: [
            { name: 'objectType', description: 'SOAP API object type name', type: 'string' },
            {
                name: 'propertiesArray',
                description: 'Array of property objects identifying the target items',
                type: 'array',
            },
            {
                name: 'action',
                description:
                    'Action to perform, typically "Start". The verb is case-insensitive at runtime ("start" works identically to "Start").',
                type: 'string',
                enum: ['Start'],
            },
            {
                name: 'performOptions',
                description: 'Properties of the SOAP PerformOptions object',
                type: 'object',
                optional: true,
            },
        ],
        returnType: 'WSProxyResult',
        returnDescription:
            'Object with Status (string, "OK" on success), StatusMessage (string, empty on success), RequestID (string) and Results (Array with one entry per input item). Each Results element carries StatusCode, StatusMessage, OrdinalID, ErrorCode plus an Object (the acted-on API object) and a Task sub-object (StatusCode, StatusMessage, InteractionObjectID, etc.).',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime (CloudPage) confirmed the (objectType, propertiesArray, action[, performOptions]) signature and the WSProxyResult return shape: Status/StatusMessage/RequestID plus a Results array with one entry per input item. Against a freshly-created active QueryDefinition, both "Start" and lowercase "start" returned Status "OK" with Results[0].StatusMessage "QueryDefinition perform called successfully" — the action verb is case-insensitive, so the docs\' Enum(\'Start\') is not case-sensitive as previously assumed. Each Results element exposes StatusCode, StatusMessage, OrdinalID, ErrorCode, an Object wrapper and a Task sub-object (with InteractionObjectID); the official docs do not detail this per-item structure.',
        syntax: '<WSProxyInstance>.performBatch(objectType, propertiesArray, action[, performOptions])',
        example:
            'var api = new Script.Util.WSProxy();\n' +
            'var items = [{ ObjectID: id1 }, { ObjectID: id2 }];\n' +
            'var result = api.performBatch("QueryDefinition", items, "Start");\n' +
            'Write(result.Status);',
    },
    {
        name: 'describe',
        isStatic: false,
        minArgs: 1,
        maxArgs: 1,
        description:
            'Returns structural metadata for one or more SOAP API object types, one ObjectDefinition per requested type.',
        params: [
            {
                name: 'objectType',
                description: 'Object type name, or an array of type names, to describe',
                type: 'string|string[]',
            },
        ],
        returnType: 'WSProxyResult',
        returnDescription:
            'Object with RequestID (string) and Results (Array). Each Results element is itself the ObjectDefinition — properties like ObjectType, Name, IsCreatable and the Properties field-definition array sit directly on Results[i], NOT under a nested Results[i].ObjectDefinition.',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'The official docs place field details at Results[0].ObjectDefinition.Properties, but at runtime each Results element is directly the ObjectDefinition (Results[0].Properties); there is no nested ObjectDefinition wrapper, and the return object exposes RequestID (not Status).',
        syntax: '<WSProxyInstance>.describe(objectType)',
        example:
            'var api = new Script.Util.WSProxy();\n' +
            'var result = api.describe("DataExtension");\n' +
            'Write(Stringify(result.Results[0].Properties));',
    },
    {
        name: 'execute',
        isStatic: false,
        minArgs: 2,
        maxArgs: 2,
        description:
            'Runs a SOAP Execute request (e.g. LogUnsubEvent), passing an array of Name/Value parameter objects and the request name.',
        params: [
            {
                name: 'parameters',
                description:
                    'Array of Name/Value parameter objects to include in the Execute call.',
                type: 'object[]',
            },
            {
                name: 'requestName',
                description: 'Name of the Execute request to run.',
                type: 'string',
                enum: ['LogUnsubEvent'],
            },
        ],
        returnType: 'WSProxyResult',
        returnDescription:
            'Object with Status (string), RequestID (string), and a Results array of per-item ExecuteResponse objects (StatusCode, StatusMessage, OrdinalID, Results, ErrorCode).',
        syntax: '<WSProxyInstance>.execute(parameters, requestName)',
        example:
            'var api = new Script.Util.WSProxy();\n' +
            'var props = [\n' +
            '    { Name: "SubscriberKey", Value: "sample@sample.com" },\n' +
            '    { Name: "EmailAddress", Value: "sample@sample.com" },\n' +
            '    { Name: "JobID", Value: 0 },\n' +
            '    { Name: "ListID", Value: 0 },\n' +
            '    { Name: "BatchID", Value: 0 }\n' +
            '];\n' +
            'var result = api.execute(props, "LogUnsubEvent");\n' +
            'Write(result.Status);',
        isConfirmed: true,
    },
    {
        name: 'setClientId',
        isStatic: false,
        minArgs: 1,
        maxArgs: 1,
        description:
            'Sets a ClientId (impersonation) context on the WSProxy instance so subsequent operations run against another business unit. Pass an object with the MID under the "ID" key (and optionally "UserID"). The call itself is never rejected; whether the following operation is allowed depends on where the script runs. From a parent BU every business unit of the account can be targeted. From a child BU only its own MID works — neither the parent nor a sibling child is reachable, and the next operation fails with a "does not have access to ClientID" status naming the executing MID and the requested one. Cross-BU work therefore has to run from a parent BU.',
        params: [
            {
                name: 'options',
                description:
                    'Object with the target ClientId properties; at least the "ID" key (target BU MID) is expected, "UserID" is optional.',
                type: 'object',
            },
        ],
        returnType: 'null',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'The official docs document setClientId() as returning void, but at runtime it returns a genuine null (=== null), not undefined.',
        syntax: '<WSProxyInstance>.setClientId(options)',
        example:
            'var api = new Script.Util.WSProxy();\n' +
            'api.setClientId({ ID: 12345 }); // target child BU by MID\n' +
            'var result = api.retrieve("DataExtension", ["Name"], {});',
    },
    {
        name: 'resetClientIds',
        isStatic: false,
        minArgs: 0,
        maxArgs: 0,
        description:
            'Clears all client IDs set on the WSProxy instance, reverting to the default execution context credentials.',
        params: [],
        returnType: 'null',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'The official docs document resetClientIds() as returning void, but at runtime it returns a genuine null (=== null), not undefined.',
        syntax: '<WSProxyInstance>.resetClientIds()',
        example:
            'var api = new Script.Util.WSProxy();\n' +
            'api.setClientId({ ID: 12345 });\n' +
            '// ... perform cross-BU operations ...\n' +
            'api.resetClientIds(); // revert to default context\n' +
            'var result = api.retrieve("DataExtension", ["Name"], {});',
    },
    {
        name: 'createBatch',
        isStatic: false,
        minArgs: 2,
        maxArgs: 3,
        isConfirmed: true,
        description: 'Creates multiple Marketing Cloud objects in a single SOAP API call.',
        params: [
            { name: 'objectType', description: 'SOAP API object type name', type: 'string' },
            {
                name: 'propertiesArray',
                description: 'Array of property objects to create',
                type: 'array',
            },
            {
                name: 'createOptions',
                description:
                    'Optional SOAP CreateOptions object (e.g. RequestType, QueuePriority).',
                type: 'object',
                optional: true,
            },
        ],
        returnType: 'WSProxyResult',
        returnDescription:
            'Object with Status (string, e.g. "OK"), RequestID (string GUID), and a Results array holding one entry per input object (each with StatusCode, StatusMessage, NewObjectID, Object, etc.).',
        syntax: '<WSProxyInstance>.createBatch(objectType, propertiesArray[, createOptions])',
        example:
            'var api = new Script.Util.WSProxy();\n' +
            'var items = [\n' +
            '    { CustomerKey: "MyDE", Properties: { Property: [{ Name: "Email", Value: "a@example.com" }] } },\n' +
            '    { CustomerKey: "MyDE", Properties: { Property: [{ Name: "Email", Value: "b@example.com" }] } }\n' +
            '];\n' +
            'var result = api.createBatch("DataExtensionObject", items);\n' +
            'Write(result.Status);',
    },
    {
        name: 'updateBatch',
        isStatic: false,
        minArgs: 2,
        maxArgs: 3,
        isConfirmed: true,
        description: 'Updates multiple Marketing Cloud objects in a single SOAP API call.',
        params: [
            { name: 'objectType', description: 'SOAP API object type name', type: 'string' },
            {
                name: 'propertiesArray',
                description: 'Array of property objects to update',
                type: 'array',
            },
            {
                name: 'updateOptions',
                description: 'Optional SOAP UpdateOptions object (e.g. { SaveOptions: [...] })',
                type: 'object',
                optional: true,
            },
        ],
        returnType: 'WSProxyResult',
        returnDescription:
            'Object with Status, RequestID, and a Results array (one entry per input item). Each Results entry carries StatusCode, StatusMessage, OrdinalID, ErrorCode, and an Object wrapper.',
        syntax: '<WSProxyInstance>.updateBatch(objectType, propertiesArray[, updateOptions])',
        example:
            'var api = new Script.Util.WSProxy();\n' +
            'var items = [\n' +
            '    { CustomerKey: "MyDE", Keys: [{ Name: "Email", Value: "a@example.com" }], Properties: [{ Name: "Status", Value: "active" }] }\n' +
            '];\n' +
            'var result = api.updateBatch("DataExtensionObject", items);\n' +
            'Write(result.Status);',
    },
    {
        name: 'deleteBatch',
        isStatic: false,
        minArgs: 2,
        maxArgs: 3,
        isConfirmed: true,
        description: 'Deletes multiple Marketing Cloud objects in a single SOAP API call.',
        params: [
            { name: 'objectType', description: 'SOAP API object type name', type: 'string' },
            {
                name: 'propertiesArray',
                description:
                    'Array of property objects identifying each object to delete. For DataExtensionObject use CustomerKey plus a flat Keys array of { Name, Value } pairs — the nested Keys.Key form accepted by deleteItem throws here.',
                type: 'array',
            },
            {
                name: 'deleteOptions',
                description:
                    'Optional SOAP DeleteOptions object (e.g. RequestType, QueuePriority).',
                type: 'object',
                optional: true,
            },
        ],
        returnType: 'WSProxyResult',
        returnDescription:
            'Object with Status (string, e.g. "OK"), RequestID (string GUID), and a Results array holding one entry per input object (each with StatusCode, StatusMessage, ErrorCode, Object, etc.). There is no top-level StatusMessage.',
        syntax: '<WSProxyInstance>.deleteBatch(objectType, propertiesArray[, deleteOptions])',
        example:
            'var api = new Script.Util.WSProxy();\n' +
            'var items = [\n' +
            '    { CustomerKey: "MyDE", Keys: [{ Name: "Email", Value: "old@example.com" }] }\n' +
            '];\n' +
            'var result = api.deleteBatch("DataExtensionObject", items);\n' +
            'Write(result.Status);',
    },
];

// ── HTTPHeader (Core library) ─────────────────────────────────────────────────
// Requires Platform.Load("core", "1") before use.

export const HTTPHEADER_METHODS = [
    {
        name: 'GetValue',
        minArgs: 1,
        maxArgs: 1,
        isStatic: false,
        requiresCoreLoad: true,
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): reads INBOUND request headers (e.g. `Host`, `User-Agent`) and ' +
            'returns their string value. It does NOT read back a header you set earlier with ' +
            '`HTTPHeader.SetValue(...)` — GetValue for a just-set custom header returns `null`. ' +
            'Treat GetValue and SetValue as operating on separate (inbound vs outbound) header collections.',
        description:
            'Retrieves the value of the specified INBOUND HTTP request header (e.g. Host, User-Agent). ' +
            'Returns `null` for headers that are not present on the request.',
        params: [{ name: 'name', description: 'Name of the HTTP header to read', type: 'string' }],
        returnType: 'string|null',
        syntax: 'HTTPHeader.GetValue(name)',
        example:
            'Platform.Load("core", "1");\n' +
            'var host = HTTPHeader.GetValue("Host");\n' +
            'Write(host);',
    },
    {
        name: 'SetValue',
        minArgs: 2,
        maxArgs: 2,
        isStatic: false,
        requiresCoreLoad: true,
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): `content-length` cannot be changed (response keeps the real body ' +
            'length). Official docs also claim `host` is protected, but `SetValue("Host", …)` emits an outbound ' +
            '`Host` header. Boolean `value` is accepted but stringified with CLR capitalization (`True`/`False`).',
        description:
            'Sets the value of the specified OUTBOUND HTTP header. ' +
            'The content-length header cannot be changed; host can be set despite official docs. ' +
            'Note: values set here are not readable via `HTTPHeader.GetValue`, which reads inbound headers.',
        params: [
            { name: 'name', description: 'Name of the header to set', type: 'string' },
            {
                name: 'value',
                description: 'Value to assign to the header',
                type: 'string|number|boolean',
            },
        ],
        returnType: 'void',
        syntax: 'HTTPHeader.SetValue(name, value)',
        example: 'Platform.Load("core", "1");\nHTTPHeader.SetValue("From", "aruiz@example.com");',
    },
    {
        name: 'Remove',
        minArgs: 1,
        maxArgs: 1,
        isStatic: false,
        requiresCoreLoad: true,
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): returns `undefined` (typeof "undefined"), NOT the `"OK"` string ' +
            'implied by some docs. Do not rely on the return value; call it for its side effect only.',
        description: 'Removes the specified entry from the HTTP header. Returns `undefined`.',
        params: [
            { name: 'headerName', description: 'Name of the header to remove', type: 'string' },
        ],
        returnType: 'void',
        syntax: 'HTTPHeader.Remove(headerName)',
        example:
            'Platform.Load("core", "1");\n' +
            'HTTPHeader.Remove("X-Custom-Header"); // no useful return value',
    },
];

// ── Script.Util HTTP constructors ────────────────────────────────────────────
// Request handler constructors under the Script.Util namespace.
// Instantiated with `new Script.Util.HttpRequest(url)` etc.

/**
 * @type {{name: string, minArgs: number, maxArgs: number, description: string, params?: {name: string, description: string, type?: string, optional?: boolean}[], returnType?: string, syntax?: string, example?: string}[]}
 */
export const SCRIPT_UTIL_CONSTRUCTORS = [
    {
        name: 'WSProxy',
        minArgs: 0,
        maxArgs: 0,
        description:
            'Creates a WSProxy instance for making SOAP API calls against the Marketing Cloud web service. ' +
            'No Platform.Load is required.',
        params: [],
        returnType: 'WSProxyInstance',
        returnDescription:
            'An authenticated WSProxy object bound to the current execution context.',
        syntax: 'new Script.Util.WSProxy()',
        example:
            'var api = new Script.Util.WSProxy();\n' +
            'var result = api.retrieve("DataExtension", ["Name", "CustomerKey"]);\n' +
            'if (result.Status === "OK") {\n' +
            '    Write(Stringify(result.Results));\n' +
            '}',
        isConfirmed: true,
    },
    {
        name: 'HttpRequest',
        minArgs: 1,
        maxArgs: 1,
        isConfirmed: true,
        description:
            'Creates an HTTP request handler that supports any HTTP method (GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS). ' +
            'Unlike Platform.Function.HTTPGet/HTTPPost, this handler supports custom methods and headers. ' +
            'Call send() to execute the request and receive a Script.Util.HttpResponse object.',
        params: [
            { name: 'url', description: 'The destination URL for the request', type: 'string' },
        ],
        returnType: 'HttpRequestInstance',
        syntax: 'new Script.Util.HttpRequest(url)',
        example:
            'var url = "https://api.example.com/items/123";\n' +
            'var req = new Script.Util.HttpRequest(url);\n' +
            'req.emptyContentHandling = 0;\n' +
            'req.retries = 2;\n' +
            'req.continueOnError = true;\n' +
            'req.contentType = "application/json";\n' +
            'req.method = "PUT";\n' +
            'req.setHeader("Authorization", "Bearer " + accessToken);\n' +
            'req.postData = Stringify({ status: "active" });\n' +
            'var resp = req.send();\n' +
            'var result = Platform.Function.ParseJSON(String(resp.content));',
    },
    {
        name: 'HttpGet',
        minArgs: 1,
        maxArgs: 1,
        isConfirmed: true,
        description:
            'Creates an HTTP GET request handler. Unlike Platform.Function.HTTPGet, this handler caches content for use in mail sends and supports custom headers. ' +
            'Only works with HTTP on port 80 and HTTPS on port 443. ' +
            'Call send() to execute the request and receive a Script.Util.HttpResponse object.',
        params: [{ name: 'url', description: 'The URL to retrieve content from', type: 'string' }],
        returnType: 'HttpGetInstance',
        syntax: 'new Script.Util.HttpGet(url)',
        example:
            'var req = new Script.Util.HttpGet("https://api.example.com/data");\n' +
            'req.setHeader("Authorization", "Bearer " + accessToken);\n' +
            'req.retries = 2;\n' +
            'req.continueOnError = true;\n' +
            'var resp = req.send();\n' +
            'if (resp.statusCode == 200) {\n' +
            '    var result = Platform.Function.ParseJSON(String(resp.content));\n' +
            '    Platform.Response.Write(Platform.Function.Stringify(result));\n' +
            '}',
    },
];

// ── Script.Util request object methods ──────────────────────────────────────
// Methods available on a request object returned by Script.Util.HttpRequest,
// Methods available on a request object returned by Script.Util.HttpRequest or Script.Util.HttpGet.

/**
 * @type {{name: string, minArgs: number, maxArgs: number, description: string, params?: {name: string, description: string, type?: string, optional?: boolean}[], returnType?: string, syntax?: string, example?: string}[]}
 */
export const SCRIPT_UTIL_REQUEST_METHODS = [
    {
        name: 'send',
        minArgs: 0,
        maxArgs: 0,
        isConfirmed: true,
        description:
            'Executes the HTTP request and returns a Script.Util.HttpResponse object. ' +
            'The response object has a `statusCode` property and a `content` property. ' +
            'Use String(resp.content) to convert the CLR content to a JavaScript string before parsing with Platform.Function.ParseJSON().',
        params: [],
        returnType: 'HttpResponseInstance',
        syntax: '<HttpRequestInstance>.send()',
        example:
            'var req = new Script.Util.HttpRequest("https://api.example.com/data");\n' +
            'req.method = "GET";\n' +
            'req.setHeader("Authorization", "Bearer " + accessToken);\n' +
            'var resp = req.send();\n' +
            'if (resp.statusCode == 200) {\n' +
            '    var result = Platform.Function.ParseJSON(String(resp.content));\n' +
            '}',
    },
    {
        name: 'setHeader',
        minArgs: 2,
        maxArgs: 2,
        isConfirmed: true,
        description:
            'Sets a request header on the Script.Util HTTP request. ' +
            'Note: setting a custom header disables content caching for Script.Util.HttpGet.',
        params: [
            {
                name: 'name',
                description: 'Header name (e.g. "Authorization", "Content-Type")',
                type: 'string',
            },
            { name: 'value', description: 'Header value', type: 'string' },
        ],
        returnType: 'void',
        syntax: '<HttpRequestInstance>.setHeader(name, value)',
        example:
            'var req = new Script.Util.HttpRequest("https://api.example.com/data");\n' +
            'req.setHeader("Authorization", "Bearer " + accessToken);\n' +
            'req.setHeader("Content-Type", "application/json");\n' +
            'var resp = req.send();',
    },
    {
        name: 'clearHeaders',
        minArgs: 0,
        maxArgs: 0,
        isConfirmed: true,
        description: 'Removes all custom headers previously set on the request.',
        params: [],
        returnType: 'void',
        syntax: '<HttpRequestInstance>.clearHeaders()',
        example:
            'var req = new Script.Util.HttpRequest("https://api.example.com/data");\n' +
            'req.setHeader("Authorization", "Bearer " + accessToken);\n' +
            'req.clearHeaders(); // removes Authorization and all other custom headers\n' +
            'var resp = req.send();',
    },
    {
        name: 'removeHeader',
        minArgs: 1,
        maxArgs: 1,
        isConfirmed: true,
        description: 'Removes a specific header from the request by name.',
        params: [{ name: 'name', description: 'Name of the header to remove', type: 'string' }],
        returnType: 'void',
        syntax: '<HttpRequestInstance>.removeHeader(name)',
        example:
            'var req = new Script.Util.HttpRequest("https://api.example.com/data");\n' +
            'req.setHeader("Authorization", "Bearer " + accessToken);\n' +
            'req.setHeader("X-Custom", "value");\n' +
            'req.removeHeader("X-Custom");\n' +
            'var resp = req.send();',
    },
];

// ── Script.Util.HttpGet writable instance properties ────────────────────────
// Configurable properties on the object returned by `new Script.Util.HttpGet(url)`.
// Source: ssjs.guide/http/script-util-httpget.md (HttpGetInstance Properties).
// This array is the SHARED BASE: every entry here exists on both request handlers,
// so SCRIPT_UTIL_REQUEST_PROPERTIES below is derived from it plus the request-only
// extras. Membership is opt-in per runtime evidence — only add a property here once
// it is proven to exist on `new Script.Util.HttpGet(url)` too.

/**
 * Writable config properties shared by the objects returned by
 * `new Script.Util.HttpGet(url)` and `new Script.Util.HttpRequest(url)`.
 *
 * `isConfirmed` marks a property whose runtime type/behaviour was validated with a
 * live CloudPage test (see docs/joern/http-introspection-*). `differsFromOfficialDocs`
 * flags an entry that contradicts the official Salesforce docs; `officialDocsNote`
 * describes that discrepancy in one sentence for rendering on ssjs.guide.
 *
 * `valueConstraint` (optional) describes the allowed literal values for the property so
 * tooling (LSP diagnostics, eslint-plugin-sfmc) can flag invalid assignments. Shapes:
 * `{ enum: [...] }` — value must be one of the listed literals (case-sensitive strings);
 * `{ numeric: 'integer' | 'number', min?: number }` — value must be a number of that kind
 * (integer = whole number), optionally >= `min`. `enumLabels` (optional) maps each enum
 * value to a short human-readable meaning used in quick-fix titles (e.g. `0` -> "continue").
 *
 * Descriptions here are handler-neutral because the same object is documented for both
 * constructors.
 *
 * @type {{name: string, type: string, description: string, isConfirmed?: boolean, differsFromOfficialDocs?: boolean, officialDocsNote?: string, valueConstraint?: {enum?: (string|number)[], enumLabels?: Object.<string, string>, numeric?: 'integer'|'number', min?: number}}[]}
 */
export const SCRIPT_UTIL_HTTPGET_PROPERTIES = [
    {
        name: 'retries',
        type: 'number',
        description: 'Number of times a failed request is retried before it gives up (default 1).',
        isConfirmed: true,
        valueConstraint: { numeric: 'integer', min: 0 },
    },
    {
        name: 'continueOnError',
        type: 'boolean',
        description:
            'If true, a failed request lets the script carry on instead of throwing an error.',
        isConfirmed: true,
    },
    {
        name: 'emptyContentHandling',
        type: 'number',
        description:
            'What to do when the request returns no content: 0 = continue, 1 = stop, 2 = continue to next subscriber (email sends only).',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'The official docs type this as a boolean, but both request handlers accept only the numeric modes 0/1/2 at runtime and reject true/false.',
        valueConstraint: {
            enum: [0, 1, 2],
            enumLabels: {
                0: 'continue',
                1: 'stop',
                2: 'continue to next subscriber - email sends only',
            },
        },
    },
    {
        name: 'timeout',
        type: 'number',
        description: 'Timeout in seconds (default 30).',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'The official docs do not list this as a configuration property on either request handler — they only state that send() gives up after 30 seconds. The property does exist and is applied end-to-end at runtime, and its default of 30 lines up with that 30-second limit, so the unit is seconds.',
        valueConstraint: { numeric: 'integer', min: 0 },
    },
];

// ── Script.Util.HttpRequest-only writable instance properties ───────────────
// Properties exposed by `new Script.Util.HttpRequest(url)` but NOT by
// `new Script.Util.HttpGet(url)` — reading them off a HttpGet instance throws
// "Object reference not set" (docs/joern/http-introspection-FINDINGS.md).
// Module-internal: consumers read the combined SCRIPT_UTIL_REQUEST_PROPERTIES export.

/**
 * `access` marks a property whose access direction is restricted at runtime.
 * See `propertyAccessLookup` for the meaning of each value.
 *
 * @type {{name: string, type: string, description: string, access?: 'write-only'|'write-only-opaque'|'read-only', isConfirmed?: boolean, differsFromOfficialDocs?: boolean, officialDocsNote?: string, valueConstraint?: {enum?: (string|number)[], enumLabels?: Object.<string, string>, numeric?: 'integer'|'number', min?: number}}[]}
 */
const SCRIPT_UTIL_REQUEST_ONLY_PROPERTIES = [
    {
        name: 'method',
        type: 'string',
        description: 'HTTP method (GET, POST, PUT, PATCH, DELETE).',
        isConfirmed: true,
        valueConstraint: { enum: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'] },
    },
    {
        name: 'contentType',
        type: 'string',
        description: 'Content-Type header for the request body, e.g. "application/json".',
        isConfirmed: true,
    },
    {
        name: 'encoding',
        type: 'string',
        description:
            'Character encoding for the request. The runtime default is "Windows-1252", not "UTF-8" — set it explicitly when the body is UTF-8. An assigned value is read back lower-cased ("UTF-8" reads back as "utf-8").',
        isConfirmed: true,
    },
    {
        name: 'postData',
        type: 'string',
        access: 'write-only',
        description:
            'Request body for POST/PUT/PATCH requests. Write-only: assignment works and the body reaches the server, but reading the property throws "Property Get method was not found." — outside a try/catch that throw aborts the whole CloudPage.',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'The official docs list postData among the readable configuration properties, but the runtime exposes no getter: every read throws "Property Get method was not found." while assignment works normally.',
    },
];

// ── Script.Util.HttpRequest writable instance properties ────────────────────
// Configurable properties on the object returned by `new Script.Util.HttpRequest(url)`.
// Source: ssjs.guide/http/script-util-httprequest.md (HttpRequestInstance Properties).
// DERIVED, never a second literal list: the shared base that HttpGet also exposes,
// followed by the request-only extras. That makes drift between the two handlers
// impossible — a shared property can only ever be edited in one place.
// These are writable (req.method = "POST"), so the generator emits them as plain
// (non-readonly) class members.

export const SCRIPT_UTIL_REQUEST_PROPERTIES = [
    ...SCRIPT_UTIL_HTTPGET_PROPERTIES,
    ...SCRIPT_UTIL_REQUEST_ONLY_PROPERTIES,
];

// ── Script.Util HTTP response instance properties ───────────────────────────
// Read-only properties on the object returned by `<HttpRequestInstance>.send()`.
// Identical for HttpRequest and HttpGet. Source: ssjs.guide HttpResponseInstance.

/**
 * @type {{name: string, type: string, description: string, isConfirmed?: boolean, differsFromOfficialDocs?: boolean, officialDocsNote?: string}[]}
 */
export const SCRIPT_UTIL_RESPONSE_PROPERTIES = [
    {
        name: 'content',
        type: 'any',
        description:
            'Response body as a CLR string — wrap with String() before use. Reading .length directly on it always yields -1 no matter how long the body is, and typeof reports "number" so the usual CLR tell is absent; measure with String(content).length instead.',
        isConfirmed: true,
    },
    {
        name: 'contentType',
        type: 'string',
        description:
            'Content type returned in the response. Always empty when the request was made with Script.Util.HttpGet — use Script.Util.HttpRequest to get it.',
        isConfirmed: true,
    },
    {
        name: 'encoding',
        type: 'string',
        description:
            'Documented as the encoding type returned in the response, but it is always an empty string at runtime — on Script.Util.HttpRequest as well as on Script.Util.HttpGet, even when the response Content-Type carries a charset. Read the charset from the content-type header instead.',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'The official docs list encoding as a populated response property, but it comes back empty for every request handler — the charset is only obtainable from the content-type header.',
    },
    {
        name: 'headers',
        type: 'object',
        description:
            'Response headers as a CLR object. Direct access (headers["X"], .Get(), .Item(), String(headers[key])) throws "Use of CLR is not allowed". To read values, enumerate with for..in: each key is the string "Name, Value" (wrapped in [ ]) — strip the brackets and split on the first ", " to build a plain header map. The enumeration is always empty when the request was made with Script.Util.HttpGet — use Script.Util.HttpRequest to read headers.',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'The official example reads a single header via headers["..."], but that access throws at runtime. Individual values are only readable by parsing the for..in enumeration keys (shaped "[Name, Value]"), not by indexing.',
    },
    {
        name: 'returnStatus',
        type: 'number',
        description:
            'Status value: 0 = OK, 1 = empty URL, 2 = call failed, 3 = succeeded with empty content. Returned as a CLR value: === against a number literal is never true and switch/case silently falls through to default, so convert once with Number() and compare the result. Do not use == — loose equality against a CLR value backed by a .NET null throws "Value cannot be null. Parameter name: value", while === returns false safely. Relational operators (<, <=, >, >=) already evaluate correctly on the raw value.',
        isConfirmed: true,
    },
    {
        name: 'statusCode',
        type: 'number',
        description:
            'HTTP status code. Returned as a CLR value: === against a number literal is never true and switch/case silently falls through to default, so convert once with Number() and compare the result. Do not use == — loose equality against a CLR value backed by a .NET null throws "Value cannot be null. Parameter name: value", while === returns false safely. Relational operators (<, <=, >, >=) already evaluate correctly on the raw value.',
        isConfirmed: true,
    },
];

// ── WSProxy result object shape ─────────────────────────────────────────────
// Shape of the object returned by the CRUD/retrieve/execute methods on a
// `new Script.Util.WSProxy()` instance. Source: ssjs.guide/wsproxy/*.md
// (Return Value sections are consistent across createItem, retrieve, execute, …).

/**
 * @type {{name: string, type: string, optional?: boolean, description: string, isConfirmed?: boolean, differsFromOfficialDocs?: boolean, officialDocsNote?: string}[]}
 */
export const WSPROXY_RESULT_PROPERTIES = [
    {
        name: 'Status',
        type: 'string',
        description:
            'Overall result status. More than the documented two values: "OK", "MoreDataAvailable" (paged retrieve), "InvalidRequest" (request rejected), "Error", or a full sentence carrying the failure text.',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): Status is NOT limited to "OK"/"Error". A paged retrieve returns ' +
            '"MoreDataAvailable"; a rejected write returns "InvalidRequest"; an unknown object type returns the ' +
            'whole message as the status value (e.g. "Error: NoSuchObjectTypeXyz is not a valid ObjectType."). ' +
            'Test for equality with "OK" rather than testing for "Error".',
    },
    {
        name: 'RequestID',
        type: 'string',
        description:
            'Server-assigned request identifier (GUID). Always present, including on failed calls; getNextBatch() echoes the same value for every page of one retrieve.',
        isConfirmed: true,
    },
    {
        name: 'Results',
        type: 'WspResult[]',
        description:
            'Array-like collection of per-object result entries (or retrieved rows for retrieve()). Null when the request itself was rejected.',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): the collection is array-LIKE but not a real JavaScript array — ' +
            '`Results instanceof Array` is false even though `.length` and `.slice` exist and index access works, ' +
            'so iterate with a classic for loop over `.length` instead of using instanceof. A retrieve that ' +
            'matches nothing yields a zero-length collection, but a rejected request (invalid ObjectType) sets ' +
            'Results to null — guard with a null check before reading `.length`.',
    },
    {
        name: 'HasMoreRows',
        type: 'boolean',
        optional: true,
        description:
            'retrieve()/getNextBatch() only: true when more rows exist — call getNextBatch() with the same RequestID. Absent (undefined) on create/update/delete/perform results.',
        isConfirmed: true,
    },
    {
        name: 'StatusMessage',
        type: 'string',
        optional: true,
        description:
            'Human-readable status message. Rarely populated at the top level — usually undefined even on failures, where the real message sits on Results[i].StatusMessage.',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): the top-level StatusMessage was undefined on every retrieve, create, ' +
            'update and delete result observed, and only present — as an EMPTY string — on performItem, where ' +
            'the actual failure text was carried by Results[0].StatusMessage. Read per-item messages from the ' +
            'Results entries; do not rely on this field.',
    },
];

// ── WSProxy per-item result entry shape ─────────────────────────────────────
// Shape of each entry in the `Results` array returned by the CRUD/perform
// methods (createItem/createBatch/updateItem/updateBatch/deleteItem/deleteBatch/
// performItem/performBatch). Runtime-proven on live CloudPages. For retrieve()/
// getNextBatch(), `Results` instead holds retrieved rows, so entries are typed as
// `WspResult` loosely (extra row fields are permitted via the index signature).
// Emitted in the generated .d.ts as `interface WspResult`.

/**
 * @type {{name: string, type: string, optional?: boolean, description: string, isConfirmed?: boolean, differsFromOfficialDocs?: boolean, officialDocsNote?: string}[]}
 */
export const WSP_RESULT_ENTRY_PROPERTIES = [
    {
        name: 'StatusCode',
        type: 'string',
        optional: true,
        description:
            'Per-item status: "OK" on success, "Error" on failure. Present on create/update/delete/perform entries; absent on rows returned by retrieve()/getNextBatch().',
        isConfirmed: true,
    },
    {
        name: 'StatusMessage',
        type: 'string',
        optional: true,
        description:
            'Per-item human-readable message. Populated on success too (e.g. "QueryDefinition deleted"), not only on failure. This — not the top-level StatusMessage — carries the real error text.',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): success entries carry a descriptive message rather than an empty ' +
            'string, so a non-empty StatusMessage does not indicate failure. Always branch on StatusCode.',
    },
    {
        name: 'OrdinalID',
        type: 'number',
        optional: true,
        description:
            'Zero-based index of the input item this entry corresponds to. Always 0 for the single-item methods (createItem/updateItem/deleteItem/performItem).',
        isConfirmed: true,
    },
    {
        name: 'ErrorCode',
        type: 'number',
        optional: true,
        description:
            'Numeric error code. Present as 0 on success AND on many failures — it is not a reliable failure signal; use StatusCode instead.',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): ErrorCode is a number (typeof "number"), not a string, and it stays 0 ' +
            'even on failed items whose StatusCode is "Error". It is never absent or empty on success as the ' +
            'docs imply — it is simply 0 in both cases.',
    },
    {
        name: 'NewID',
        type: 'number',
        optional: true,
        description:
            'Numeric ID assigned to a newly created object. Only present on create results; undefined on update, delete, perform and retrieve entries.',
        isConfirmed: true,
    },
    {
        name: 'NewObjectID',
        type: 'string',
        optional: true,
        description:
            'GUID assigned to a newly created object. Only present on create results for object types that use ObjectID keys; undefined on update, delete, perform and retrieve entries.',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Not documented alongside NewID, but returned at runtime on create results. Use it (not NewID) when ' +
            'the follow-up call needs an ObjectID GUID, e.g. deleting or performing a freshly created ' +
            'QueryDefinition or DataExtension.',
    },
    {
        name: 'Object',
        type: 'object',
        optional: true,
        description:
            'Echo of the affected object as returned by the API — the payload you sent plus server-populated fields (ObjectID, CreatedDate, ModifiedDate, Client, PartnerKey, ObjectState, …). Present on both success and failure entries.',
        isConfirmed: true,
    },
    {
        name: 'Task',
        type: 'object',
        optional: true,
        description:
            'perform-only: async task descriptor with StatusCode, StatusMessage, OrdinalID, ErrorCode, ID, TblAsyncID and InteractionObjectID. Present for performItem()/performBatch(); undefined elsewhere.',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): Task.StatusCode can read "OK" and Task.InteractionObjectID can hold a ' +
            'GUID even when the enclosing result Status is "InvalidRequest" and Results[0].StatusCode is ' +
            '"Error" — the task was created but not queued. Task.ID is null and Task.TblAsyncID is 0 in that ' +
            'state, so never treat a populated Task as proof the action ran; check the outer Status and ' +
            'Results[i].StatusCode first.',
    },
    {
        name: 'RequestID',
        type: 'string',
        optional: true,
        description:
            'Per-entry request identifier. Observed as null on every result entry at runtime — read the top-level RequestID instead.',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): present as a key on the entry but always null, on both success and ' +
            'failure. The usable request identifier is the top-level RequestID on the result object.',
    },
];
