// Barrel: re-exports the full public API from the split raw-data modules and
// the derived layer. Preserves the exact named-export surface of the former
// monolithic src/index.js (93 exports). Do not add logic here.

export { VERIFICATION_BLOCKED_REASONS } from './constants.js';
export { SSJS_GLOBALS } from './globals.js';
export { PLATFORM_FUNCTIONS } from './platform-functions.js';
export {
    PLATFORM_METHODS,
    PLATFORM_VARIABLE_METHODS,
    PLATFORM_RESPONSE_METHODS,
    PLATFORM_REQUEST_METHODS,
    REQUEST_UTILITY_METHODS,
    PLATFORM_RECIPIENT_METHODS,
    ATTRIBUTE_METHODS,
    DATE_TIME_METHODS,
    DATE_TIME_TIMEZONE_METHODS,
    ERROR_UTIL_METHODS,
} from './platform-methods.js';
export {
    CORE_LIBRARY_OBJECTS,
    ACCOUNT_METHODS,
    ACCOUNT_TRACKING_METHODS,
    ACCOUNT_USER_METHODS,
    PORTFOLIO_METHODS,
    CONTENT_AREA_OBJ_METHODS,
    FOLDER_METHODS,
    TEMPLATE_METHODS,
    DELIVERY_PROFILE_METHODS,
    SENDER_PROFILE_METHODS,
    SEND_CLASSIFICATION_METHODS,
    FILTER_DEFINITION_METHODS,
    QUERY_DEFINITION_METHODS,
    LIST_METHODS,
    LIST_SUBSCRIBERS_METHODS,
    LIST_SUBSCRIBERS_TRACKING_METHODS,
    SUBSCRIBER_METHODS,
    SUBSCRIBER_ATTRIBUTES_METHODS,
    SUBSCRIBER_LISTS_METHODS,
    EMAIL_METHODS,
    SEND_METHODS,
    SEND_TRACKING_METHODS,
    SEND_TRACKING_CLICKS_METHODS,
    SEND_TRACKING_TOTAL_BY_INTERVAL_METHODS,
    SEND_DEFINITION_METHODS,
    TRIGGERED_SEND_METHODS,
    TRIGGERED_SEND_TRACKING_METHODS,
    TRIGGERED_SEND_TRACKING_CLICKS_METHODS,
    TRIGGERED_SEND_TRACKING_TOTAL_BY_INTERVAL_METHODS,
    EVENT_METHODS,
    DATA_EXTENSION_METHODS,
    DATA_EXTENSION_FIELDS_METHODS,
    DATA_EXTENSION_ROWS_METHODS,
} from './core-library.js';
export {
    HTTP_METHODS,
    WSPROXY_METHODS,
    HTTPHEADER_METHODS,
    SCRIPT_UTIL_CONSTRUCTORS,
    SCRIPT_UTIL_REQUEST_METHODS,
    SCRIPT_UTIL_HTTPGET_PROPERTIES,
    SCRIPT_UTIL_REQUEST_PROPERTIES,
    SCRIPT_UTIL_RESPONSE_PROPERTIES,
    WSPROXY_RESULT_PROPERTIES,
    WSP_RESULT_ENTRY_PROPERTIES,
} from './http-wsproxy.js';
export { ECMASCRIPT_BUILTINS, CONSTRUCTIBLE_BUILTINS } from './ecmascript.js';
export { UNSUPPORTED_SYNTAX, KNOWN_UNSUPPORTED } from './unsupported.js';
export { POLYFILLABLE_METHODS } from './polyfills.js';
export {
    SSJS_GLOBALS_MAP,
    notDefinedAtRuntimeGlobalNames,
    notDefinedAtRuntimeGlobalLookup,
    platformFunctionLookup,
    platformFunctionNames,
    coreObjectNames,
    coreObjectLookup,
    httpMethodNames,
    wsproxyMethodNames,
    httpHeaderMethodNames,
    platformRecipientMethodNames,
    attributeMethodNames,
    unsupportedByNodeType,
    polyfillByPrototypeName,
    polyfillByStaticName,
    knownUnsupportedByPrototypeName,
    knownUnsupportedByStaticName,
    platformResponseLookup,
    platformVariableLookup,
    platformRequestLookup,
    requestUtilityLookup,
    platformRecipientLookup,
    httpMethodLookup,
    httpHeaderMethodLookup,
    wsproxyMethodLookup,
    attributeMethodLookup,
    ssjsGlobalsLookup,
    coreMethodArityLookup,
    coreNonFunctionalMethodLookup,
    coreDeprecatedMethodLookup,
    maxCoreVersionLookup,
    propertyAccessLookup,
} from './derived.js';
