// Generated by splitting the former monolithic src/index.js.
// Raw data module: platform-methods.js. Re-exported by src/index.js (the barrel).

// ── Top-level Platform methods ───────────────────────────────────────────────
// Direct methods on the Platform object (e.g. Platform.Load).

export const PLATFORM_METHODS = [
    {
        name: 'Load',
        minArgs: 2,
        maxArgs: 2,
        description: 'Loads a platform library. Must be called before using Core library objects.',
        params: [
            { name: 'libraryName', description: 'Library to load (e.g. "core")', type: 'string' },
            { name: 'version', description: 'Library version (e.g. "1.1.5")', type: 'string' },
        ],
        returnType: 'null',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'The docs describe Platform.Load as void, but it returns the literal null; never test the result ' +
            'to detect success because a failed load throws. The documented required libraryName accepts an ' +
            'empty string or null as a silent no-op, while "core" is matched case-insensitively. Accepted ' +
            'versions include "1", "1.0", "1.1", "1.0.0" and revisions "1.1.0" through "1.1.6"; later ' +
            'revisions and other major or minor versions are rejected. 32767 selects the newest version in ' +
            'the minor or revision slot, but not the major slot. Loading Core enables bare-name aliases such ' +
            'as Variable, Attribute and DataExtension; Platform.* objects are already available without it. ' +
            'The load spans the whole request, and repeated loads are harmless.',
        syntax: 'Platform.Load(libraryName, version)',
        example:
            'Platform.Load("core", "1.1.5");\nvar de = DataExtension.Init("MyDE");\nvar rows = de.Rows.Retrieve();',
    },
];

// ── Platform.Variable / Platform.Response / Platform.Request ─────────────────

export const PLATFORM_VARIABLE_METHODS = [
    {
        name: 'GetValue',
        minArgs: 1,
        maxArgs: 1,
        description: 'Retrieves the value of an AMPscript variable from the SSJS context.',
        params: [
            { name: 'variableName', description: 'Name of the AMPscript variable', type: 'string' },
        ],
        returnType: 'string|number|boolean|null',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified (CloudPage GET): values retain their SSJS scalar type within the request, while a ' +
            'never-set variable returns JavaScript `null` and an explicitly empty variable returns `""`. The ' +
            'leading `@` is optional, and variable names are case-insensitive.',
        syntax: 'Platform.Variable.GetValue(variableName)',
        example:
            'var sk = Platform.Variable.GetValue("SubscriberKey");\n' +
            'Write(sk);\n' +
            '// Bare-name alias: Variable.GetValue("SubscriberKey")',
    },
    {
        name: 'SetValue',
        minArgs: 2,
        maxArgs: 2,
        description: 'Assigns a value to an AMPscript variable from the SSJS context.',
        params: [
            { name: 'variableName', description: 'Name of the AMPscript variable', type: 'string' },
            {
                name: 'value',
                description: 'Scalar value to assign',
                type: 'string|number|boolean|null|undefined',
            },
        ],
        returnType: 'null',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified (CloudPage GET): the method returns JavaScript `null`, not void. Strings, numbers, ' +
            'and booleans retain their SSJS scalar type in later SSJS blocks; null and undefined read back as ' +
            '`null`. The leading `@` is optional, and values are request-local.',
        syntax: 'Platform.Variable.SetValue(variableName, value)',
        example:
            'Platform.Variable.SetValue("greeting", "Hello from SSJS");\n' +
            '// @greeting is now available in subsequent AMPscript blocks\n' +
            '// Bare-name alias: Variable.SetValue("greeting", "Hello from SSJS")',
    },
];

export const PLATFORM_RESPONSE_METHODS = [
    {
        name: 'SetResponseHeader',
        minArgs: 2,
        maxArgs: 2,
        description: 'Sets a response header on the current page response.',
        params: [
            { name: 'headerName', description: 'Name of the response header.', type: 'string' },
            { name: 'value', description: 'Value for the response header.', type: 'string' },
        ],
        returnType: 'null',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): the header appears verbatim in the HTTP response and the call returns JavaScript null, not void. ' +
            'Numeric values are coerced to their string form.',
        syntax: 'Platform.Response.SetResponseHeader(headerName, value)',
        example:
            'Platform.Response.SetResponseHeader("Content-Type", "application/json");\nPlatform.Response.Write(Stringify({ status: "ok" }));',
    },
    {
        name: 'RemoveResponseHeader',
        minArgs: 1,
        maxArgs: 1,
        description: 'Removes a previously set HTTP response header from the response.',
        params: [
            {
                name: 'headerName',
                description: 'Name of the HTTP response header to remove.',
                type: 'string',
            },
        ],
        returnType: 'null',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): removes a header set earlier in the same request and returns JavaScript null, not void. ' +
            'Removing a header that was never set is a no-op rather than an error.',
        syntax: 'Platform.Response.RemoveResponseHeader(headerName)',
        example: 'Platform.Response.RemoveResponseHeader("X-Powered-By");',
    },
    {
        name: 'Redirect',
        minArgs: 1,
        maxArgs: 2,
        description:
            'Redirects the current page to a new URL and stops script execution immediately. ' +
            'Pass false for a 302 temporary redirect or true for a 301 permanent redirect; ' +
            'omitting the flag also yields a 302. ' +
            'Do not use 301 if you want browsers to re-check the original URL later.',
        params: [
            { name: 'url', description: 'URL to redirect to.', type: 'string' },
            {
                name: 'movedPermanently',
                description:
                    'True for 301 permanent redirect, false for 302 temporary. Defaults to a 302 when omitted.',
                type: 'boolean',
                optional: true,
            },
        ],
        returnType: 'void',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified (CloudPage). Behaviours the official docs do not state: ' +
            'the second argument is optional — a single-argument call produces a 302 with the Location header set; ' +
            'a successful redirect discards any response body already written; ' +
            'and a redirect inside try is catchable — the catch runs and can call Redirect again, ' +
            'overriding the Location (keep redirects out of try, or guard the catch).',
        syntax: 'Platform.Response.Redirect(url[, movedPermanently])',
        example: 'Platform.Response.Redirect("https://pub.pages.example.com/thank-you", false);',
    },
    {
        name: 'SetCookie',
        minArgs: 2,
        maxArgs: 4,
        description: 'Sets a cookie on the client browser response.',
        params: [
            { name: 'name', description: 'Name of the cookie to set.', type: 'string' },
            { name: 'value', description: 'Value to store in the cookie.', type: 'string' },
            {
                name: 'expires',
                description:
                    'Expiration date/time for the cookie. Accepts a date string or a JavaScript Date object.',
                type: 'string|Date',
                optional: true,
            },
            {
                name: 'secure',
                description: 'If true, the cookie is only sent over HTTPS.',
                type: 'boolean',
                optional: true,
            },
        ],
        returnType: 'null',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): each call returns JavaScript null, not void, and emits its own Set-Cookie header. ' +
            'Without an expiry the cookie is a session cookie; a JavaScript Date object is accepted for ' +
            'the expiry alongside a date string and is rendered as a GMT timestamp.',
        syntax: 'Platform.Response.SetCookie(name, value[, expires, secure])',
        example: 'Platform.Response.SetCookie("userId", subscriberKey, "12/31/2025", true);',
    },
    {
        name: 'RemoveCookie',
        minArgs: 1,
        maxArgs: 1,
        description:
            'Attempts to remove a browser cookie from a CloudPage response. In the tested runtime it returns null but emits no deletion header; use SetCookie with an empty value and a past JavaScript Date instead.',
        params: [{ name: 'name', description: 'Name of the cookie to remove.', type: 'string' }],
        returnType: 'null',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified on a published CloudPage GET with the named request cookie present: the call returns JavaScript null, not void, and emits no Set-Cookie header. ' +
            'The proven workaround is SetCookie(name, "", new Date(1970, 0, 1), true), which emits an empty cookie with a past expiry and removes it from the next cookie-jar request.',
        syntax: 'Platform.Response.RemoveCookie(name)',
        example: 'Platform.Response.SetCookie("userId", "", new Date(1970, 0, 1), true);',
    },
    {
        name: 'Write',
        minArgs: 1,
        maxArgs: 1,
        description:
            'Writes content to the HTTP response output. ' +
            'Distinct from the bare-name `Write()`, which also writes to the response after Core load. ' +
            'Non-string values use CLR stringification (not JS toString); use Stringify for objects.',
        params: [
            {
                name: 'content',
                description: 'Content string to write to the response.',
                type: 'string',
            },
        ],
        returnType: 'void',
        isConfirmed: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): writes directly to the HTTP response body and returns JavaScript null. ' +
            'Non-string values use CLR stringification — objects/arrays emit host type names, booleans emit ' +
            '`True`/`False` — matching bare-name Write.',
        syntax: 'Platform.Response.Write(content)',
        example:
            'var data = { name: "Jane", status: "active" };\nPlatform.Response.Write(Stringify(data));',
    },
    // ── Response properties (no parentheses — isProperty: true) ──────────────
    {
        name: 'ContentType',
        minArgs: 0,
        maxArgs: 0,
        isProperty: true,
        access: 'write-only-opaque',
        description:
            'Sets the Content-Type of the HTTP response. Reading or calling the property returns an opaque platform-managed CLR value rather than the configured MIME type.',
        params: [],
        returnType: 'clr',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): assignment works and is reflected in the HTTP Content-Type header. ' +
            'Reading or calling the property does not return the configured string; it returns an opaque CLR value with no documented caller-facing use. ' +
            'Keep your own JavaScript variable if the value must be read later.',
        syntax: 'Platform.Response.ContentType',
        example: 'Platform.Response.ContentType = "application/json";',
    },
    {
        name: 'CharacterSet',
        minArgs: 0,
        maxArgs: 0,
        isProperty: true,
        access: 'write-only-opaque',
        description:
            'Sets the character set of the HTTP response. Reading or calling the property returns an opaque platform-managed CLR value rather than the configured character set.',
        params: [],
        returnType: 'clr',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): assignment works and is reflected in the charset parameter of the HTTP Content-Type header. ' +
            'Reading or calling the property does not return the configured string; it returns an opaque CLR value with no documented caller-facing use. ' +
            'Keep your own JavaScript variable if the value must be read later.',
        syntax: 'Platform.Response.CharacterSet',
        example: 'Platform.Response.CharacterSet = "UTF-8";',
    },
];

export const PLATFORM_REQUEST_METHODS = [
    {
        name: 'GetQueryStringParameter',
        minArgs: 1,
        maxArgs: 1,
        description: 'Retrieves the value of a URL query string parameter.',
        params: [
            {
                name: 'parameterName',
                description: 'Name of the query string parameter.',
                type: 'string',
            },
        ],
        returnType: 'string|null',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified (CloudPage GET): an absent parameter returns strict JavaScript `null`, not an ' +
            'empty string. Empty values return `""`; repeated values are comma-joined in URL order; names are ' +
            'case-insensitive; plus signs, percent escapes, and UTF-8 sequences are decoded; numeric names are ' +
            'coerced to strings. Guard reads with truthiness or `!= null`.',
        syntax: 'Platform.Request.GetQueryStringParameter(parameterName)',
        example:
            '// Page URL: /mypage?email=jane@example.com\nvar email = Platform.Request.GetQueryStringParameter("email");\nWrite(email);',
    },
    {
        name: 'GetFormField',
        minArgs: 1,
        maxArgs: 1,
        description:
            'Retrieves a named field from a submitted POST form body. On a CloudPage GET it does not fall back ' +
            'to query parameters and returns null.',
        params: [
            { name: 'name', description: 'Name of the form field to retrieve.', type: 'string' },
        ],
        returnType: 'string|null',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified (CloudPage GET): it returns strict JavaScript `null` for an absent field and does ' +
            'not read a same-named query-string parameter. Use GetQueryStringParameter for URL values.',
        syntax: 'Platform.Request.GetFormField(name)',
        example: 'var email = Platform.Request.GetFormField("emailAddress");\nWrite(email);',
    },
    {
        name: 'GetPostData',
        minArgs: 0,
        maxArgs: 1,
        description:
            'Returns the raw body of the HTTP POST request. ' +
            'CAVEAT: Only returns data on the FIRST call per request; subsequent calls return nothing. ' +
            'Store the result in a variable if you need it multiple times.',
        params: [
            {
                name: 'encoding',
                description: 'Character encoding for the post data.',
                type: 'string',
                optional: true,
            },
        ],
        returnType: 'string',
        isConfirmed: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): on a GET request it returns `""` ' +
            '(empty string), not null. First call per request returns the body; subsequent calls return `""`.',
        syntax: 'Platform.Request.GetPostData([encoding])',
        example:
            '// Read raw POST body once and store it:\nvar rawBody = Platform.Request.GetPostData();\nvar payload = Platform.Function.ParseJSON(rawBody);',
    },
    {
        name: 'GetCookieValue',
        minArgs: 1,
        maxArgs: 1,
        description:
            'Retrieves the value of a named cookie from the HTTP request sent by the client browser.',
        params: [
            { name: 'cookieName', description: 'Name of the cookie to retrieve.', type: 'string' },
        ],
        returnType: 'string|null',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): a supplied cookie returns its string value; an absent cookie returns ' +
            'strict JavaScript `null`, not an empty string.',
        syntax: 'Platform.Request.GetCookieValue(cookieName)',
        example:
            'var sessionId = Platform.Request.GetCookieValue("sessionId");\nif (sessionId) { Write("Session: " + sessionId); }',
    },
    {
        name: 'GetUserLanguages',
        minArgs: 0,
        maxArgs: 0,
        description:
            'Returns the language preferences of the client browser as specified in the HTTP Accept-Language request header.',
        params: [],
        returnType: 'string',
        isConfirmed: true,
        notDefinedAtRuntime: true,
        officialDocsNote:
            'Officially documented to return the `Accept-Language` header value, but `GetUserLanguages()` as ' +
            'called is NOT DEFINED AT RUNTIME: the engine does not resolve this member — runtime probing shows ' +
            'it throws the generic `System.InvalidOperationException: "Unable to retrieve security descriptor ' +
            'for this frame."` at every arity tried (0/1/2 args), the error the SSJS engine raises for an ' +
            'unrecognized member name or an argument count the engine does not accept (NOT a security or ' +
            'frame restriction). The same `Accept-Language` header IS present and readable in the same run via ' +
            '`Platform.Request.GetRequestHeader("Accept-Language")`. Use ' +
            '`Platform.Request.GetRequestHeader("Accept-Language")` instead, which returns the same value ' +
            'this method is documented to expose.',
        syntax: 'Platform.Request.GetUserLanguages()',
        example:
            'var lang = Platform.Request.GetUserLanguages();\nWrite(lang); // e.g. "en-US,en;q=0.9"',
    },
    {
        name: 'GetRequestHeader',
        minArgs: 1,
        maxArgs: 1,
        description: 'Returns the value of the named HTTP request header, or null if not present.',
        params: [
            {
                name: 'headerName',
                description: 'Name of the HTTP request header to retrieve.',
                type: 'string',
            },
        ],
        returnType: 'string|null',
        isConfirmed: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): header names are case-insensitive; a supplied header returns its string ' +
            'value and an absent header returns strict JavaScript `null`.',
        syntax: 'Platform.Request.GetRequestHeader(headerName)',
        example:
            'var auth = Platform.Request.GetRequestHeader("Authorization");\nif (auth) { Write("Auth: " + auth); }',
    },
    // ── Request properties (no parentheses — isProperty: true) ───────────────
    {
        name: 'Browser',
        minArgs: 0,
        maxArgs: 0,
        isProperty: true,
        access: 'read-only',
        description:
            'Returns an object describing the client browser, parsed from the User-Agent request header.',
        params: [],
        returnType: 'object',
        isConfirmed: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): returns a CLR object exposing `Platform`, `Browser`, `Version`, ' +
            '`MajorVersion`, and `MinorVersion`. Individual fields read fine by name, but the object is not ' +
            'enumerable — `for...in` yields no keys — so address the fields directly. `Stringify()` does render ' +
            'the whole object. When the request carries no User-Agent header the fields fall back to ' +
            '"Unknown" / version 0 rather than throwing. Read-only: assigning to it fails.',
        syntax: 'Platform.Request.Browser',
        example: 'var browser = Platform.Request.Browser;\nWrite(Stringify(browser));',
    },
    {
        name: 'ClientIP',
        minArgs: 0,
        maxArgs: 0,
        isProperty: true,
        access: 'read-only',
        description: 'Returns the IP address of the client.',
        params: [],
        returnType: 'string',
        isConfirmed: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): returns the caller IP address. The value is a CLR string ' +
            '(`typeof` reports `clr`), so compare it after an explicit `String()` conversion rather than with ' +
            '`===`. Read-only: assigning to it fails.',
        syntax: 'Platform.Request.ClientIP',
        example: 'Write(Platform.Request.ClientIP);',
    },
    {
        name: 'HasSSL',
        minArgs: 0,
        maxArgs: 0,
        isProperty: true,
        access: 'read-only',
        description: 'Returns true if the current request was made over HTTPS.',
        params: [],
        returnType: 'boolean',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): the value is a CLR boolean, not a JavaScript one — `typeof` reports ' +
            '`clr` and it renders as "True"/"False". It is truthy/falsy as expected in an `if`, but strict ' +
            'comparison against `true` or against the string "True" both fail. Test it directly in a condition ' +
            'instead of comparing with `===`. Read-only: assigning to it fails.',
        syntax: 'Platform.Request.HasSSL',
        example:
            'if (Platform.Request.HasSSL) {\n    Write("Secure connection");\n} else {\n    Platform.Response.Redirect("https://" + Platform.Request.RequestURL);\n}',
    },
    {
        name: 'IsSSL',
        minArgs: 0,
        maxArgs: 0,
        isProperty: true,
        access: 'read-only',
        description: 'Returns true if the current request was made over HTTPS (alias of HasSSL).',
        params: [],
        returnType: 'boolean',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): resolves and returns the same value as `HasSSL` in the same request. ' +
            'Like `HasSSL` it is a CLR boolean (`typeof` reports `clr`, renders as "True"/"False") and fails ' +
            'strict comparison against `true` or "True" — use it directly in a condition. Read-only.',
        syntax: 'Platform.Request.IsSSL',
        example: 'Write(Platform.Request.IsSSL);',
    },
    {
        name: 'Method',
        minArgs: 0,
        maxArgs: 0,
        isProperty: true,
        access: 'read-only',
        description: 'Returns the HTTP method (GET, POST, etc.) of the current request.',
        params: [],
        returnType: 'string',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): returns the uppercase HTTP verb. The value is a CLR string ' +
            '(`typeof` reports `clr`), so a strict comparison such as `Method === "POST"` never matches — ' +
            'wrap it in `String()` first. Read-only: assigning to it fails.',
        syntax: 'Platform.Request.Method',
        example:
            'var method = String(Platform.Request.Method);\nif (method === "POST") {\n    var body = Platform.Request.GetPostData();\n    // handle POST\n}',
    },
    {
        name: 'QueryString',
        minArgs: 0,
        maxArgs: 0,
        isProperty: true,
        access: 'read-only',
        description: 'Returns the full query string of the current request URL.',
        params: [],
        returnType: 'string',
        isConfirmed: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): includes the leading `?`. A request without a query string yields ' +
            'an empty value rather than null or a throw. The value is a CLR string (`typeof` reports `clr`), ' +
            'so convert with `String()` before comparing. Read-only.',
        syntax: 'Platform.Request.QueryString',
        example: 'Write(Platform.Request.QueryString);',
    },
    {
        name: 'ReferrerURL',
        minArgs: 0,
        maxArgs: 0,
        isProperty: true,
        access: 'read-only',
        description: 'Returns the referrer URL from the HTTP Referer header.',
        params: [],
        returnType: 'string',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): returns the Referer header when one is sent, but when the header is ' +
            'ABSENT reading the property THROWS a null-reference error instead of returning null or an empty ' +
            'string — a plain link click or address-bar visit is enough to trigger it. Always wrap the read in ' +
            'a try/catch, or read the header via `Platform.Request.GetRequestHeader("Referer")`, which returns ' +
            'null when absent. The value is a CLR string; read-only.',
        syntax: 'Platform.Request.ReferrerURL',
        example:
            'var referrer = "";\ntry {\n    referrer = String(Platform.Request.ReferrerURL);\n} catch (ex) {\n    // no Referer header was sent\n}\nWrite(referrer);',
    },
    {
        name: 'RequestURL',
        minArgs: 0,
        maxArgs: 0,
        isProperty: true,
        access: 'read-only',
        description: 'Returns the full URL of the current page request.',
        params: [],
        returnType: 'string',
        isConfirmed: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): returns the absolute URL including scheme, host, path, and the query ' +
            'string when present. Always populated. The value is a CLR string (`typeof` reports `clr`), ' +
            'so convert with `String()` before comparing. Read-only.',
        syntax: 'Platform.Request.RequestURL',
        example: 'Write("Current page: " + Platform.Request.RequestURL);',
    },
    {
        name: 'UserAgent',
        minArgs: 0,
        maxArgs: 0,
        isProperty: true,
        access: 'read-only',
        description: 'Returns the user-agent string from the HTTP request.',
        params: [],
        returnType: 'string',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): returns the User-Agent header when one is sent, but when the header ' +
            'is ABSENT reading the property THROWS a null-reference error instead of returning null or an empty ' +
            'string. Wrap the read in a try/catch, or use ' +
            '`Platform.Request.GetRequestHeader("User-Agent")`, which returns null when absent. Note that ' +
            '`Platform.Request.Browser` stays readable in the same situation and reports "Unknown" instead of ' +
            'throwing. The value is a CLR string; read-only.',
        syntax: 'Platform.Request.UserAgent',
        example:
            'var agent = "";\ntry {\n    agent = String(Platform.Request.UserAgent);\n} catch (ex) {\n    // no User-Agent header was sent\n}\nWrite(agent);',
    },
];

// ── Core Library "Request Object Utility Functions" methods ──────────────────
// The bare-name Core `Request` object (available after Platform.Load("core","1"))
// exposes these zero-arg utility METHODS plus the single-argument value getters
// GetQueryStringParameter and GetFormField. This is a DIFFERENT, distinct object
// from Platform.Request (which uses PROPERTIES like RequestURL and CLR methods) —
// not an alias of it. For example `Request.URL()` is a real METHOD here whereas on
// Platform.Request the equivalent is the `RequestURL` PROPERTY.
// Runtime-verified on a published CloudPage: the six context
// methods invoke cleanly (URL() returns the full URL; Method() returns the HTTP verb;
// the rest return empty strings outside their populating context), and the two value
// getters return the query-string value for a present key (null for an absent key).
// Referenced by the generator via PLATFORM_NAMESPACE_MAP['Request'].
export const REQUEST_UTILITY_METHODS = [
    {
        name: 'URL',
        minArgs: 0,
        maxArgs: 0,
        requiresCoreLoad: true,
        description: 'Returns the full URL of the current page request.',
        params: [],
        returnType: 'string',
        isConfirmed: true,
        officialDocsNote:
            'Runtime-verified (CloudPage GET): returns the full request URL as a string ' +
            '(e.g. `https://…pub.sfmc-content.com/hovt2pwtcq3`). This is a distinct Core object ' +
            'method, not an alias of `Platform.Request` — the equivalent there is the ' +
            '`RequestURL` PROPERTY, not a `URL()` method.',
        syntax: 'Request.URL()',
        example: 'var requestURL = Request.URL();\nWrite(requestURL);',
    },
    {
        name: 'PagePath',
        minArgs: 0,
        maxArgs: 0,
        requiresCoreLoad: true,
        description: 'Returns the path portion of the current page request.',
        params: [],
        returnType: 'string',
        isConfirmed: true,
        officialDocsNote:
            'Runtime-verified (CloudPage GET): invokes cleanly and returns an empty string ' +
            '(`""`) outside its populating context. This is a distinct Core object method, ' +
            'not an alias of `Platform.Request`.',
        syntax: 'Request.PagePath()',
        example: 'var path = Request.PagePath();\nWrite(path);',
    },
    {
        name: 'Method',
        minArgs: 0,
        maxArgs: 0,
        requiresCoreLoad: true,
        description: 'Returns the HTTP method (GET, POST, etc.) of the current request.',
        params: [],
        returnType: 'string',
        isConfirmed: true,
        officialDocsNote:
            'Runtime-verified (CloudPage GET): returns the HTTP verb as a string (e.g. `"GET"`). ' +
            'This is a distinct Core object method, not an alias of `Platform.Request` — the ' +
            'equivalent there is the `Method` PROPERTY.',
        syntax: 'Request.Method()',
        example: 'var method = Request.Method();\nWrite(method);',
    },
    {
        name: 'ApplicationID',
        minArgs: 0,
        maxArgs: 0,
        requiresCoreLoad: true,
        description: 'Returns the application ID associated with the current request.',
        params: [],
        returnType: 'string',
        isConfirmed: true,
        officialDocsNote:
            'Runtime-verified (CloudPage GET): invokes cleanly and returns an empty string ' +
            '(`""`) outside its populating context. This is a distinct Core object method, ' +
            'not an alias of `Platform.Request`.',
        syntax: 'Request.ApplicationID()',
        example: 'var appId = Request.ApplicationID();\nWrite(appId);',
    },
    {
        name: 'PackageID',
        minArgs: 0,
        maxArgs: 0,
        requiresCoreLoad: true,
        description: 'Returns the package ID associated with the current request.',
        params: [],
        returnType: 'string',
        isConfirmed: true,
        officialDocsNote:
            'Runtime-verified (CloudPage GET): invokes cleanly and returns an empty string ' +
            '(`""`) outside its populating context. This is a distinct Core object method, ' +
            'not an alias of `Platform.Request`.',
        syntax: 'Request.PackageID()',
        example: 'var packageId = Request.PackageID();\nWrite(packageId);',
    },
    {
        name: 'ApplicationBaseURL',
        minArgs: 0,
        maxArgs: 0,
        requiresCoreLoad: true,
        description: 'Returns the base URL of the application for the current request.',
        params: [],
        returnType: 'string',
        isConfirmed: true,
        officialDocsNote:
            'Runtime-verified (CloudPage GET): invokes cleanly and returns an empty string ' +
            '(`""`) outside its populating context. This is a distinct Core object method, ' +
            'not an alias of `Platform.Request`.',
        syntax: 'Request.ApplicationBaseURL()',
        example: 'var baseUrl = Request.ApplicationBaseURL();\nWrite(baseUrl);',
    },
    {
        name: 'GetQueryStringParameter',
        minArgs: 1,
        maxArgs: 1,
        requiresCoreLoad: true,
        description:
            'Returns the value of a named URL query string parameter for the current page request, or null when the parameter is absent.',
        params: [
            {
                name: 'name',
                description: 'Key name of the query string parameter to read.',
                type: 'string|number',
            },
        ],
        returnType: 'string',
        isConfirmed: true,
        officialDocsNote:
            'Runtime-verified on a published CloudPage GET (?probeParam=hello): Request.GetQueryStringParameter("probeParam") returned "hello" (typeof "string"); an absent key returned null (typeof "object"). Unlike the CLR-backed Platform.Request.GetQueryStringParameter, this bare-name Core method is a Jint function: calling it with zero arguments returns null and a surplus second argument is ignored (it does NOT throw the "Unable to retrieve security descriptor for this frame." arity error). This is a distinct Core object method, not an alias of Platform.Request.GetQueryStringParameter. Guard reads with a truthiness / != null check.',
        syntax: 'Request.GetQueryStringParameter(name)',
        example:
            'var sku = Request.GetQueryStringParameter("sku");\nif (sku) { Write("SKU: " + sku); }',
    },
    {
        name: 'GetFormField',
        minArgs: 1,
        maxArgs: 1,
        requiresCoreLoad: true,
        description:
            'Returns the value of a named form field submitted with the current request (POST form data), or null when the field is absent. Does not read GET query string parameters — use Request.GetQueryStringParameter for those.',
        params: [
            {
                name: 'name',
                description: 'Name of the form field to read.',
                type: 'string',
            },
        ],
        returnType: 'string',
        isConfirmed: true,
        officialDocsNote:
            'Runtime-verified on a published CloudPage GET (?probeParam=hello): Request.GetFormField("probeParam") returned null (typeof "object") even though the same key was present in the query string — it does not read GET query parameters (use Request.GetQueryStringParameter). An absent key also returned null. This bare-name Core method is a Jint function: calling it with zero arguments or a surplus second argument does NOT throw the "Unable to retrieve security descriptor for this frame." arity error (it returns null / ignores the extra argument), unlike the CLR-backed Platform.Request.GetFormField. Populated POST form values were not exercised in the GET probe; a POST request is needed to observe a non-null return. This is a distinct Core object method, not an alias of Platform.Request.GetFormField. Guard reads with a truthiness / != null check.',
        syntax: 'Request.GetFormField(name)',
        example: 'var email = Request.GetFormField("emailAddress");\nif (email) { Write(email); }',
    },
];

// ── Platform.Recipient methods ───────────────────────────────────────────────
// Methods available under Platform.Recipient.* for accessing recipient/subscriber
// attribute values and sendable data extension fields during email sends.

export const PLATFORM_RECIPIENT_METHODS = [
    {
        name: 'GetAttributeValue',
        minArgs: 1,
        maxArgs: 1,
        description:
            'Returns the value of a subscriber attribute or sendable data extension field for the current recipient.',
        params: [
            {
                name: 'attributeName',
                description: 'Name of the subscriber attribute or sendable DE field to retrieve',
                type: 'string',
            },
        ],
        returnType: 'string',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): does NOT throw outside a send ' +
            'context — in a plain CloudPage it returns `""` (empty string, typeof "string") for any attribute ' +
            'because no recipient is bound. The bare-name `Recipient` alias is NOT available even after ' +
            'Platform.Load; use `Platform.Recipient.GetAttributeValue(...)` (or `Attribute.GetValue(...)` after load).',
        syntax: 'Platform.Recipient.GetAttributeValue(attributeName)',
        example:
            'var email = Platform.Recipient.GetAttributeValue("EmailAddress");\nPlatform.Response.Write(email);',
    },
];

// ── Attribute methods ────────────────────────────────────────────────────────
// Methods on the bare `Attribute` global. Require Platform.Load("core", "1.1.5").
// Preferred over Platform.Recipient.GetAttributeValue() for readability.

export const ATTRIBUTE_METHODS = [
    {
        name: 'GetValue',
        minArgs: 1,
        maxArgs: 1,
        isStatic: true,
        requiresCoreLoad: true,
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified on a published CloudPage: after Platform.Load("Core", ...) the Attribute object exists and Attribute.GetValue(name) executes and returns a string — it is NOT unavailable in CloudPages. When no subscriber/attribute is in context (e.g. a plain CloudPage GET) it returns an empty string rather than throwing. In email/triggered-send/personalized contexts it returns the actual attribute value.',
        description:
            'Returns the value of the specified subscriber attribute or sendable data extension field for the current recipient. ' +
            'Preferred over Platform.Recipient.GetAttributeValue() — both methods are equivalent. ' +
            'Available in CloudPages after Platform.Load("Core", ...); returns an empty string when no recipient/attribute context is present.',
        params: [
            {
                name: 'name',
                description: 'Name of the subscriber attribute or sendable DE field to retrieve.',
                type: 'string',
            },
        ],
        returnType: 'string',
        syntax: 'Attribute.GetValue(name)',
        example:
            'Platform.Load("Core", "1.1.1");\n' +
            'var email = Attribute.GetValue("EmailAddress");\n' +
            'Write(email);',
    },
];

// ── DateTime methods ─────────────────────────────────────────────────────────
// Short-form date-time conversion helpers on the DateTime namespace.
// Require Platform.Load("core", "1.1.5").

export const DATE_TIME_METHODS = [
    {
        name: 'SystemDateToLocalDate',
        minArgs: 1,
        maxArgs: 1,
        description:
            'Converts a date-time value from Marketing Cloud system time (CST) to the local time of the account or user. Returns a Date object.',
        params: [
            {
                name: 'dateString',
                description: 'Date-time value in system time (CST); string or Date',
                type: 'string|Date',
            },
        ],
        returnType: 'Date',
        requiresCoreLoad: true,
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): the `DateTime.SystemDateToLocalDate` bare-name form behaves IDENTICALLY to ' +
            '`Platform.Function.SystemDateToLocalDate` (same value, same type). The official docs type the return as a ' +
            'string, but the runtime returns a genuine Date object: typeof "object", `Object.prototype.toString` reports ' +
            '"[object Date]", `.constructor === Date`, and `getFullYear()`/`getHours()`/`getTime()` all work (identical ' +
            'to `new Date()`). The only anomaly is that `instanceof Date` returns false, due to the engine-wide ' +
            '`instanceof`-on-builtins bug — detect via `.constructor === Date`, not `instanceof`. It coerces to an ' +
            'ISO-like string when written or stringified. SCOPE RULE: bare-name Core globals exist ONLY after ' +
            'Platform.Load("core", ...) has run — call the load first.',
        syntax: 'DateTime.SystemDateToLocalDate(dateString)',
        example:
            'Platform.Load("core", "1.1.5");\nvar localTime = DateTime.SystemDateToLocalDate(Platform.Function.Now());\nWrite(localTime);',
    },
    {
        name: 'LocalDateToSystemDate',
        minArgs: 1,
        maxArgs: 1,
        description:
            'Converts a date-time value from the local time of the account or user to Marketing Cloud system time (CST). Returns a Date object.',
        params: [
            {
                name: 'dateString',
                description: 'Date-time value in local account/user time; string or Date',
                type: 'string|Date',
            },
        ],
        returnType: 'Date',
        requiresCoreLoad: true,
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): the `DateTime.LocalDateToSystemDate` bare-name form behaves IDENTICALLY to ' +
            '`Platform.Function.LocalDateToSystemDate` (same value, same type). The official docs type the return as a ' +
            'string, but the runtime returns a genuine Date object: typeof "object", `Object.prototype.toString` reports ' +
            '"[object Date]", `.constructor === Date`, and `getFullYear()`/`getHours()`/`getTime()` all work (identical ' +
            'to `new Date()`). The only anomaly is that `instanceof Date` returns false, due to the engine-wide ' +
            '`instanceof`-on-builtins bug — detect via `.constructor === Date`, not `instanceof`. It coerces to an ' +
            'ISO-like string when written or stringified. SCOPE RULE: bare-name Core globals exist ONLY after ' +
            'Platform.Load("core", ...) has run — call the load first.',
        syntax: 'DateTime.LocalDateToSystemDate(dateString)',
        example:
            'Platform.Load("core", "1.1.5");\nvar systemTime = DateTime.LocalDateToSystemDate("8/5/2025 12:34 PM");\nWrite(systemTime);',
    },
];

// ── DateTime.TimeZone methods ────────────────────────────────────────────────
// Methods on the DateTime.TimeZone namespace. Require Platform.Load("core", "1.1.5").

export const DATE_TIME_TIMEZONE_METHODS = [
    {
        name: 'Retrieve',
        minArgs: 0,
        maxArgs: 1,
        isStatic: true,
        requiresCoreLoad: true,
        isConfirmed: true,
        officialDocsNote:
            'Runtime-verified (CloudPage). `Platform.Load("core", ...)` is genuinely required — before the load ' +
            '`DateTime` is undefined and the call throws. The filter argument is optional: calling it with no ' +
            'argument returns the full time-zone list. Each result carries `ID` (number) and `Name` (string). ' +
            'A filter that matches nothing returns an empty list rather than null, so callers can read `.length` ' +
            'unconditionally. The returned value behaves as a JavaScript array — it is indexable, exposes ' +
            '`.length`, reports "[object Array]" and carries array methods such as `push` and `slice`; only ' +
            '`instanceof Array` is false, which is the engine-wide instanceof-on-builtins bug rather than ' +
            'anything specific to this method. ' +
            'A malformed filter (a plain string, or an object without the three filter properties) raises a ' +
            'time-zone retrieval error instead of returning an empty list.',
        description:
            'Retrieves an array of time zones matching the specified filter criteria. ' +
            'If no filter is supplied the function returns all available time zones.',
        params: [
            {
                name: 'filter',
                description:
                    'Filter criteria object with properties: `Property`, `SimpleOperator`, `Value`. ' +
                    'Omit it to retrieve every time zone.',
                type: 'object',
                optional: true,
            },
        ],
        returnType: 'object[]',
        syntax: 'DateTime.TimeZone.Retrieve([filter])',
        example:
            'Platform.Load("core", "1.1.5");\n' +
            'var timezones = DateTime.TimeZone.Retrieve({ Property: "ID", SimpleOperator: "equals", Value: 1 });\n' +
            'Write(Stringify(timezones));',
    },
];

// ── ErrorUtil methods ────────────────────────────────────────────────────────
// Utility functions for WSProxy error handling. Require Platform.Load("core", "1.1.5").

export const ERROR_UTIL_METHODS = [
    {
        name: 'ThrowWSProxyError',
        minArgs: 1,
        maxArgs: 1,
        isStatic: true,
        requiresCoreLoad: true,
        deprecated: true,
        maxCoreVersion: '1',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified (CloudPage): `ErrorUtil` (and its only member `ThrowWSProxyError`) is provided ' +
            'ONLY by `Platform.Load("Core", "1")`. Under any newer Core version ("1.1.1", "1.1.5", …) `ErrorUtil` ' +
            'is `undefined`, so this call throws a TypeError ("Object expected: ThrowWSProxyError") — it is ' +
            'effectively deprecated in Core > 1. ' +
            'A preceding `new Script.Util.WSProxy()` is NOT required to make ErrorUtil available (disproven at runtime). ' +
            'When it does throw on a real WSProxy error result, it throws a plain STRING (e.g. ' +
            '"Error: Data extension does not exist: …") — not an Error object — so the caught value has no ' +
            '`.message`/`.description` (both `undefined`); read the string itself via `String(ex)`. ' +
            'On the success path it does not return `undefined`: it returns the result `Status` string ("OK"). ' +
            'Recommended replacement (works on any Core version): inspect `result.Status` and ' +
            '`throw new Error(...)` (or handle inline) instead of calling ErrorUtil.ThrowWSProxyError.',
        description:
            'Inspects a WSProxy result object and throws when its `Status` property indicates an error. ' +
            'WSProxy methods never raise exceptions on SOAP-level errors — instead they return a result ' +
            'object whose `Status` field signals the outcome. ' +
            'DEPRECATED: only available under `Platform.Load("Core", "1")`; unavailable in newer Core versions. ' +
            'Prefer checking `result.Status` and throwing `new Error(...)` yourself.',
        params: [
            {
                name: 'result',
                description:
                    'Result object returned by any WSProxy method. ' +
                    'Minimum shape: `{ Status: string, RequestID: string, Results: object[] }`. ' +
                    'Retrieve and perform variants may include additional fields.',
                type: 'object',
            },
        ],
        returnType: 'string',
        returnDescription:
            'The `Status` string of the passed result (e.g. `"OK"`) when it indicates success. ' +
            'Throws instead of returning when `Status` indicates an error.',
        syntax: 'ErrorUtil.ThrowWSProxyError(result)',
        example:
            '// Only works under Platform.Load("Core", "1"); prefer the result.Status check below.\n' +
            'Platform.Load("Core", "1");\n' +
            'var api = new Script.Util.WSProxy();\n' +
            'var customerKey = "0b744ffa-bab5-458d-9e7d-fb05a7873380";\n' +
            'try {\n' +
            '    var result = api.retrieve(\n' +
            '        "DataExtensionObject[" + customerKey + "]",\n' +
            '        ["FirstName", "LastName", "EmailAddress"]\n' +
            '    );\n' +
            '    // Preferred, version-independent replacement:\n' +
            '    if (String(result.Status).indexOf("Error") === 0) {\n' +
            '        throw new Error(String(result.Status));\n' +
            '    }\n' +
            '    // process successful results\n' +
            '} catch (ex) {\n' +
            '    Write(String(ex));\n' +
            '}',
    },
];
