// Generated by splitting the former monolithic src/index.js.
// Raw data module: polyfills.js. Re-exported by src/index.js (the barrel).

// ── Polyfillable Array methods ────────────────────────────────────────────────
// SFMC SSJS runs on an old ECMAScript 3/5 engine that lacks many Array methods.
// Each entry below describes either a missing method (category: 'unavailable')
// or one that exists natively but returns wrong results (category: 'broken').
// The polyfill strings are rewritten originals based on patterns documented at
// https://gortonington.com/javascript-array-methods-in-sfmc/
//
// `esVersion` records the ECMAScript edition that standardized the member
// (3 = ES3, 5 = ES5, 6 = ES6/ES2015+). It is documentation-only metadata
// surfaced on ssjs.guide and is NOT consumed by any LSP/MCP/VSCE/ESLint logic.
// Note: a member can be standardized in ES3 (e.g. Array.splice) yet still be
// broken in the SFMC engine, which is why ES3 appears here too.

/**
 * @type {{method: string, owner: string, esVersion: 3 | 5 | 6, isStatic: boolean, category: 'unavailable' | 'broken', ambiguousWithString: boolean, description: string, polyfill: string}[]}
 */
export const POLYFILLABLE_METHODS = [
    {
        method: 'copyWithin',
        owner: 'Array.prototype',
        returnType: 'array',
        isConfirmed: true,
        esVersion: 6,
        isStatic: false,
        category: 'unavailable',
        ambiguousWithString: false,
        description: 'Array.prototype.copyWithin is not available in SFMC SSJS.',
        polyfill:
            '/**\n' +
            ' * Polyfill for Array.prototype.copyWithin (SFMC SSJS).\n' +
            ' * @param {number} targetIndex - index to copy the sequence to\n' +
            ' * @param {number} [startIndex] - index to start copying from\n' +
            ' * @param {number} [count] - number of elements to copy\n' +
            ' * @returns {Array} the modified array\n' +
            ' */\n' +
            'Array.prototype.copyWithin = Array.prototype.copyWithin || function (targetIndex, startIndex, count) {\n' +
            '    var n = count || 1;\n' +
            '    for (var i = 0; i < n; i++) {\n' +
            '        this[targetIndex + i] = this[startIndex + i];\n' +
            '    }\n' +
            '    return this;\n' +
            '};',
    },
    {
        method: 'entries',
        owner: 'Array.prototype',
        returnType: 'object',
        isConfirmed: true,
        esVersion: 6,
        isStatic: false,
        category: 'unavailable',
        ambiguousWithString: false,
        description: 'Array.prototype.entries is not available in SFMC SSJS.',
        polyfill:
            '/**\n' +
            ' * Polyfill for Array.prototype.entries (SFMC SSJS).\n' +
            ' * @returns {object} an iterator of [index, value] pairs\n' +
            ' */\n' +
            'Array.prototype.entries = Array.prototype.entries || function () {\n' +
            '    var index = 0;\n' +
            '    var arr = this;\n' +
            '    return {\n' +
            '        next: function () {\n' +
            '            if (index < arr.length) {\n' +
            '                return { value: [index, arr[index++]], done: false };\n' +
            '            }\n' +
            '            return { done: true };\n' +
            '        }\n' +
            '    };\n' +
            '};',
    },
    {
        method: 'fill',
        owner: 'Array.prototype',
        returnType: 'array',
        isConfirmed: true,
        esVersion: 6,
        isStatic: false,
        category: 'unavailable',
        ambiguousWithString: false,
        description: 'Array.prototype.fill is not available in SFMC SSJS.',
        polyfill:
            '/**\n' +
            ' * Polyfill for Array.prototype.fill (SFMC SSJS).\n' +
            ' * @param {*} value - value to fill the array with\n' +
            ' * @param {number} [startIndex] - index to start filling at (default 0)\n' +
            ' * @param {number} [endIndex] - index to stop filling at (default array length)\n' +
            ' * @returns {Array} the modified array\n' +
            ' */\n' +
            'Array.prototype.fill = Array.prototype.fill || function (value, startIndex, endIndex) {\n' +
            '    var start = startIndex || 0;\n' +
            '    var end = (!endIndex || endIndex > this.length) ? this.length : endIndex;\n' +
            '    for (var i = start; i < end; i++) {\n' +
            '        this[i] = value;\n' +
            '    }\n' +
            '    return this;\n' +
            '};',
    },
    {
        method: 'filter',
        owner: 'Array.prototype',
        returnType: 'array',
        isConfirmed: true,
        esVersion: 5,
        isStatic: false,
        category: 'unavailable',
        ambiguousWithString: false,
        description: 'Array.prototype.filter is not available in SFMC SSJS.',
        polyfill:
            '/**\n' +
            ' * Polyfill for Array.prototype.filter (SFMC SSJS).\n' +
            ' * @param {Function} predicate - test called with (element, index, array)\n' +
            ' * @returns {Array} a new array of elements that passed the test\n' +
            ' */\n' +
            'Array.prototype.filter = Array.prototype.filter || function (predicate) {\n' +
            "    if (typeof predicate !== 'function') { return []; }\n" +
            '    var result = [];\n' +
            '    for (var i = 0; i < this.length; i++) {\n' +
            '        if (predicate(this[i], i, this)) { result.push(this[i]); }\n' +
            '    }\n' +
            '    return result;\n' +
            '};',
    },
    {
        method: 'find',
        owner: 'Array.prototype',
        returnType: 'any',
        isConfirmed: true,
        esVersion: 6,
        isStatic: false,
        category: 'unavailable',
        ambiguousWithString: false,
        description: 'Array.prototype.find is not available in SFMC SSJS.',
        polyfill:
            '/**\n' +
            ' * Polyfill for Array.prototype.find (SFMC SSJS).\n' +
            ' * @param {Function} predicate - test called with (element, index, array)\n' +
            ' * @returns {*} the first matching element, or undefined\n' +
            ' */\n' +
            'Array.prototype.find = Array.prototype.find || function (predicate) {\n' +
            "    if (typeof predicate !== 'function') { return undefined; }\n" +
            '    for (var i = 0; i < this.length; i++) {\n' +
            '        if (predicate(this[i], i, this)) { return this[i]; }\n' +
            '    }\n' +
            '    return undefined;\n' +
            '};',
    },
    {
        method: 'findIndex',
        owner: 'Array.prototype',
        returnType: 'number',
        isConfirmed: true,
        esVersion: 6,
        isStatic: false,
        category: 'unavailable',
        ambiguousWithString: false,
        description: 'Array.prototype.findIndex is not available in SFMC SSJS.',
        polyfill:
            '/**\n' +
            ' * Polyfill for Array.prototype.findIndex (SFMC SSJS).\n' +
            ' * @param {Function} predicate - test called with (element, index, array)\n' +
            ' * @returns {number} the index of the first match, or -1\n' +
            ' */\n' +
            'Array.prototype.findIndex = Array.prototype.findIndex || function (predicate) {\n' +
            "    if (typeof predicate !== 'function') { return -1; }\n" +
            '    for (var i = 0; i < this.length; i++) {\n' +
            '        if (predicate(this[i], i, this)) { return i; }\n' +
            '    }\n' +
            '    return -1;\n' +
            '};',
    },
    {
        method: 'forEach',
        owner: 'Array.prototype',
        returnType: 'undefined',
        isConfirmed: true,
        esVersion: 5,
        isStatic: false,
        category: 'unavailable',
        ambiguousWithString: false,
        description: 'Array.prototype.forEach is not available in SFMC SSJS.',
        polyfill:
            '/**\n' +
            ' * Polyfill for Array.prototype.forEach (SFMC SSJS).\n' +
            ' * @param {Function} callback - called with (element, index, array)\n' +
            ' * @returns {void}\n' +
            ' */\n' +
            'Array.prototype.forEach = Array.prototype.forEach || function (callback) {\n' +
            "    if (typeof callback !== 'function') { return; }\n" +
            '    for (var i = 0; i < this.length; i++) {\n' +
            '        callback(this[i], i, this);\n' +
            '    }\n' +
            '};',
    },
    {
        method: 'includes',
        owner: 'Array.prototype',
        returnType: 'boolean',
        isConfirmed: true,
        esVersion: 6,
        isStatic: false,
        category: 'unavailable',
        ambiguousWithString: false,
        description: 'Array.prototype.includes is not available in SFMC SSJS.',
        polyfill:
            '/**\n' +
            ' * Polyfill for Array.prototype.includes (SFMC SSJS).\n' +
            ' * @param {*} searchValue - value to search for\n' +
            ' * @returns {boolean} true when the value is found\n' +
            ' */\n' +
            'Array.prototype.includes = Array.prototype.includes || function (searchValue) {\n' +
            '    for (var i = 0; i < this.length; i++) {\n' +
            '        if (this[i] === searchValue) { return true; }\n' +
            '    }\n' +
            '    return false;\n' +
            '};',
    },
    {
        method: 'indexOf',
        owner: 'Array.prototype',
        returnType: 'number',
        isConfirmed: true,
        esVersion: 5,
        isStatic: false,
        category: 'unavailable',
        ambiguousWithString: true,
        description: 'Array.prototype.indexOf is not available in SFMC SSJS.',
        polyfill:
            '/**\n' +
            ' * Polyfill for Array.prototype.indexOf (SFMC SSJS).\n' +
            ' * @param {*} searchValue - value to search for\n' +
            ' * @param {number} [fromIndex] - index to start searching from (default 0)\n' +
            ' * @returns {number} the first matching index, or -1\n' +
            ' */\n' +
            'Array.prototype.indexOf = Array.prototype.indexOf || function (searchValue, fromIndex) {\n' +
            '    var start = fromIndex || 0;\n' +
            '    for (var i = start; i < this.length; i++) {\n' +
            '        if (this[i] === searchValue) { return i; }\n' +
            '    }\n' +
            '    return -1;\n' +
            '};',
    },
    {
        method: 'lastIndexOf',
        owner: 'Array.prototype',
        returnType: 'number',
        isConfirmed: true,
        esVersion: 5,
        isStatic: false,
        category: 'broken',
        ambiguousWithString: true,
        description:
            'Array.prototype.lastIndexOf exists in SFMC SSJS but always returns -1. A polyfill is needed for correct results.',
        polyfill:
            '/**\n' +
            ' * Polyfill for Array.prototype.lastIndexOf (SFMC SSJS).\n' +
            ' * @param {*} searchValue - value to search for\n' +
            ' * @param {number} [fromIndex] - index to start searching backwards from (default last index)\n' +
            ' * @returns {number} the last matching index, or -1\n' +
            ' */\n' +
            'Array.prototype.lastIndexOf = function (searchValue, fromIndex) {\n' +
            '    var start = (fromIndex !== undefined) ? fromIndex : this.length - 1;\n' +
            '    for (var i = start; i >= 0; i--) {\n' +
            '        if (this[i] === searchValue) { return i; }\n' +
            '    }\n' +
            '    return -1;\n' +
            '};',
    },
    {
        method: 'map',
        owner: 'Array.prototype',
        returnType: 'array',
        isConfirmed: true,
        esVersion: 5,
        isStatic: false,
        category: 'unavailable',
        ambiguousWithString: false,
        description: 'Array.prototype.map is not available in SFMC SSJS.',
        polyfill:
            '/**\n' +
            ' * Polyfill for Array.prototype.map (SFMC SSJS).\n' +
            ' * @param {Function} callback - called with (element, index, array); its return value becomes the new element\n' +
            ' * @returns {Array} a new array of the callback results\n' +
            ' */\n' +
            'Array.prototype.map = Array.prototype.map || function (callback) {\n' +
            "    if (typeof callback !== 'function') { return []; }\n" +
            '    var result = [];\n' +
            '    for (var i = 0; i < this.length; i++) {\n' +
            '        result.push(callback(this[i], i, this));\n' +
            '    }\n' +
            '    return result;\n' +
            '};',
    },
    {
        method: 'reduce',
        owner: 'Array.prototype',
        returnType: 'any',
        isConfirmed: true,
        esVersion: 5,
        isStatic: false,
        category: 'unavailable',
        ambiguousWithString: false,
        description: 'Array.prototype.reduce is not available in SFMC SSJS.',
        polyfill:
            '/**\n' +
            ' * Polyfill for Array.prototype.reduce (SFMC SSJS).\n' +
            ' * @param {Function} callback - called with (accumulator, element, index, array)\n' +
            ' * @param {*} [initialValue] - initial accumulator value; defaults to the first element\n' +
            ' * @returns {*} the final accumulated value\n' +
            ' */\n' +
            'Array.prototype.reduce = Array.prototype.reduce || function (callback, initialValue) {\n' +
            "    if (typeof callback !== 'function') { return initialValue; }\n" +
            '    var accumulator = (arguments.length > 1) ? initialValue : this[0];\n' +
            '    var startIndex = (arguments.length > 1) ? 0 : 1;\n' +
            '    for (var i = startIndex; i < this.length; i++) {\n' +
            '        accumulator = callback(accumulator, this[i], i, this);\n' +
            '    }\n' +
            '    return accumulator;\n' +
            '};',
    },
    {
        method: 'reduceRight',
        owner: 'Array.prototype',
        returnType: 'any',
        isConfirmed: true,
        esVersion: 5,
        isStatic: false,
        category: 'unavailable',
        ambiguousWithString: false,
        description: 'Array.prototype.reduceRight is not available in SFMC SSJS.',
        polyfill:
            '/**\n' +
            ' * Polyfill for Array.prototype.reduceRight (SFMC SSJS).\n' +
            ' * @param {Function} callback - called with (accumulator, element, index, array), iterating right to left\n' +
            ' * @param {*} [initialValue] - initial accumulator value; defaults to the last element\n' +
            ' * @returns {*} the final accumulated value\n' +
            ' */\n' +
            'Array.prototype.reduceRight = Array.prototype.reduceRight || function (callback, initialValue) {\n' +
            "    if (typeof callback !== 'function') { return initialValue; }\n" +
            '    var accumulator = (arguments.length > 1) ? initialValue : this[this.length - 1];\n' +
            '    var startIndex = (arguments.length > 1) ? this.length - 1 : this.length - 2;\n' +
            '    for (var i = startIndex; i >= 0; i--) {\n' +
            '        accumulator = callback(accumulator, this[i], i, this);\n' +
            '    }\n' +
            '    return accumulator;\n' +
            '};',
    },
    {
        method: 'some',
        owner: 'Array.prototype',
        returnType: 'boolean',
        isConfirmed: true,
        esVersion: 5,
        isStatic: false,
        category: 'unavailable',
        ambiguousWithString: false,
        description: 'Array.prototype.some is not available in SFMC SSJS.',
        polyfill:
            '/**\n' +
            ' * Polyfill for Array.prototype.some (SFMC SSJS).\n' +
            ' * @param {Function} predicate - test called with (element, index, array)\n' +
            ' * @returns {boolean} true when the predicate passes for any element\n' +
            ' */\n' +
            'Array.prototype.some = Array.prototype.some || function (predicate) {\n' +
            "    if (typeof predicate !== 'function') { return false; }\n" +
            '    for (var i = 0; i < this.length; i++) {\n' +
            '        if (predicate(this[i], i, this)) { return true; }\n' +
            '    }\n' +
            '    return false;\n' +
            '};',
    },
    {
        method: 'every',
        owner: 'Array.prototype',
        returnType: 'boolean',
        isConfirmed: true,
        esVersion: 5,
        isStatic: false,
        category: 'unavailable',
        ambiguousWithString: false,
        description: 'Array.prototype.every is not available in SFMC SSJS.',
        polyfill:
            '/**\n' +
            ' * Polyfill for Array.prototype.every (SFMC SSJS).\n' +
            ' * @param {Function} predicate - test called with (element, index, array)\n' +
            ' * @returns {boolean} true when the predicate passes for every element\n' +
            ' */\n' +
            'Array.prototype.every = Array.prototype.every || function (predicate) {\n' +
            "    if (typeof predicate !== 'function') { return true; }\n" +
            '    for (var i = 0; i < this.length; i++) {\n' +
            '        if (!predicate(this[i], i, this)) { return false; }\n' +
            '    }\n' +
            '    return true;\n' +
            '};',
    },
    {
        method: 'splice',
        owner: 'Array.prototype',
        returnType: 'array',
        isConfirmed: true,
        esVersion: 3,
        isStatic: false,
        category: 'broken',
        ambiguousWithString: false,
        caveat: 'Only the two-argument delete form splice(start, deleteCount) works (deleteCount is clamped to the remaining length). The one-argument form splice(start) throws, and the insert form overwrites from the left instead of splicing. Apply the shipped polyfill for those cases.',
        description:
            'Array.prototype.splice(start, deleteCount, item1, …, itemN) works in SFMC SSJS only for the two-argument delete form splice(start, deleteCount) (deleteCount may exceed the remaining length). The one-argument form splice(start) throws "Index was outside the bounds of the array." The insert form is also broken: as soon as a third argument (item1) is passed, the engine ignores start and deleteCount and just overwrites from the left with the items to insert. A polyfill is needed for the one-argument delete form and for any insert; it also accepts unlimited additional items. Verified on a CloudPage.',
        polyfill:
            '/**\n' +
            ' * Polyfill for Array.prototype.splice (SFMC SSJS).\n' +
            ' * @param {number} start - index at which to start changing the array\n' +
            ' * @param {number} [deleteCount] - number of elements to remove (default: all from start)\n' +
            ' * @param {...*} [items] - elements to insert at start\n' +
            ' * @returns {Array} an array of the removed elements\n' +
            ' */\n' +
            'Array.prototype.splice = function (start, deleteCount) {\n' +
            '    var arr = this;\n' +
            '    var len = arr.length;\n' +
            '    start = start < 0 ? (len + start < 0 ? 0 : len + start) : (start > len ? len : start);\n' +
            '    var removeCount = arguments.length < 2 ? len - start : (deleteCount < 0 ? 0 : deleteCount);\n' +
            '    if (removeCount > len - start) { removeCount = len - start; }\n' +
            '    var endIndex = start + removeCount;\n' +
            '    var before = [];\n' +
            '    var removed = [];\n' +
            '    var after = [];\n' +
            '    for (var i = 0; i < len; i++) {\n' +
            '        if (i < start) { before.push(arr[i]); }\n' +
            '        else if (i < endIndex) { removed.push(arr[i]); }\n' +
            '        else { after.push(arr[i]); }\n' +
            '    }\n' +
            '    for (var j = 2; j < arguments.length; j++) {\n' +
            '        before.push(arguments[j]);\n' +
            '    }\n' +
            '    var merged = before.concat(after);\n' +
            '    var maxLen = arr.length > merged.length ? arr.length : merged.length;\n' +
            '    for (var k = 0; k < maxLen; k++) {\n' +
            '        if (k < merged.length) { arr[k] = merged[k]; }\n' +
            '        else { arr.pop(); }\n' +
            '    }\n' +
            '    return removed;\n' +
            '};',
    },
    {
        method: 'trim',
        owner: 'String.prototype',
        returnType: 'string',
        isConfirmed: true,
        esVersion: 5,
        isStatic: false,
        category: 'unavailable',
        ambiguousWithString: false,
        description: 'String.prototype.trim is not available in SFMC SSJS.',
        polyfill:
            '/**\n' +
            ' * Polyfill for String.prototype.trim (SFMC SSJS).\n' +
            ' * @returns {string} the string with leading and trailing whitespace removed\n' +
            ' */\n' +
            'String.prototype.trim = String.prototype.trim || function () {\n' +
            "    return this.replace(/^[\\s\\uFEFF\\xA0]+|[\\s\\uFEFF\\xA0]+$/g, '');\n" +
            '};',
    },
    {
        method: 'startsWith',
        owner: 'String.prototype',
        returnType: 'boolean',
        isConfirmed: true,
        esVersion: 6,
        isStatic: false,
        category: 'unavailable',
        ambiguousWithString: false,
        description: 'String.prototype.startsWith is not available in SFMC SSJS.',
        polyfill:
            '/**\n' +
            ' * Polyfill for String.prototype.startsWith (SFMC SSJS).\n' +
            ' * @param {string} searchString - characters to search for at the start\n' +
            ' * @param {number} [position] - position to start searching from (default 0)\n' +
            ' * @returns {boolean} true when the string starts with searchString\n' +
            ' */\n' +
            'String.prototype.startsWith = String.prototype.startsWith || function (searchString, position) {\n' +
            '    position = position || 0;\n' +
            '    return this.indexOf(searchString, position) === position;\n' +
            '};',
    },
    {
        method: 'endsWith',
        owner: 'String.prototype',
        returnType: 'boolean',
        isConfirmed: true,
        esVersion: 6,
        isStatic: false,
        category: 'unavailable',
        ambiguousWithString: false,
        description: 'String.prototype.endsWith is not available in SFMC SSJS.',
        // NOTE: the second parameter must NOT be named `length`. A function parameter named
        // `length` collides with the SSJS engine's internal length intrinsic and throws
        // "invalid length" at runtime (verified on a CloudPage). It is renamed to
        // `endPosition` here. An empty search string is short-circuited to `true` because
        // `substring(len, len)` does not reliably yield an empty string on this engine.
        polyfill:
            '/**\n' +
            ' * Polyfill for String.prototype.endsWith (SFMC SSJS).\n' +
            ' * @param {string} searchString - characters to search for at the end\n' +
            ' * @param {number} [endPosition] - position treated as the end of the string (default string length)\n' +
            ' * @returns {boolean} true when the string ends with searchString\n' +
            ' */\n' +
            'String.prototype.endsWith = String.prototype.endsWith || function (searchString, endPosition) {\n' +
            '    var str = String(this);\n' +
            '    var search = String(searchString);\n' +
            '    if (search.length === 0) { return true; }\n' +
            '    var strLen = str.length;\n' +
            '    var end = (endPosition === undefined || endPosition > strLen) ? strLen : Number(endPosition);\n' +
            '    if (end < 0) { end = 0; }\n' +
            '    var start = end - search.length;\n' +
            '    if (start < 0) { return false; }\n' +
            '    return str.substring(start, end) === search;\n' +
            '};',
    },
    {
        method: 'bind',
        owner: 'Function.prototype',
        returnType: 'any',
        isConfirmed: true,
        esVersion: 5,
        isStatic: false,
        category: 'unavailable',
        ambiguousWithString: false,
        description:
            'Function.prototype.bind is not available in SFMC SSJS, and Function.prototype is sealed so it cannot be installed on the prototype. Use the standalone bindFn helper instead: bindFn(fn, thisArg[, ...preArgs]) returns a new function with `this` and any leading arguments pre-bound. (call() and apply() are available natively.)',
        polyfill:
            '/**\n' +
            ' * Standalone replacement for the sealed Function.prototype bind method (SFMC SSJS).\n' +
            ' * @param {Function} fn - the function to bind\n' +
            ' * @param {*} thisArg - the value to use as `this` when calling fn\n' +
            ' * @param {...*} [preArgs] - arguments to prepend to every call\n' +
            ' * @returns {Function} a new function with `this` and leading arguments pre-bound\n' +
            ' */\n' +
            'function bindFn(fn, thisArg) {\n' +
            '    var preArgs = [];\n' +
            '    for (var i = 2; i < arguments.length; i++) { preArgs.push(arguments[i]); }\n' +
            '    return function () {\n' +
            '        var callArgs = [];\n' +
            '        for (var a = 0; a < preArgs.length; a++) { callArgs.push(preArgs[a]); }\n' +
            '        for (var b = 0; b < arguments.length; b++) { callArgs.push(arguments[b]); }\n' +
            '        return fn.apply(thisArg, callArgs);\n' +
            '    };\n' +
            '}',
    },
    {
        method: 'toISOString',
        owner: 'Date.prototype',
        returnType: 'string',
        isConfirmed: true,
        esVersion: 5,
        isStatic: false,
        category: 'unavailable',
        ambiguousWithString: false,
        description:
            'Date.prototype.toISOString is not available in SFMC SSJS (typeof d.toISOString is undefined; calling it throws "Object expected: toISOString"). ' +
            'Date.prototype.toJSON is also absent because it depends on toISOString. Installing a working method on Date.prototype is unreliable here, ' +
            'so use the standalone toISOStringUTC helper instead: toISOStringUTC(date) builds the ISO 8601 UTC string from the working getUTC* getters.',
        polyfill:
            '/**\n' +
            ' * Standalone replacement for the missing Date.prototype.toISOString (SFMC SSJS).\n' +
            ' * @param {Date} d - the date to serialize\n' +
            ' * @returns {string} the date in ISO 8601 UTC form, e.g. "2026-06-18T00:00:00Z"\n' +
            ' */\n' +
            'function toISOStringUTC(d) {\n' +
            "    function pad(n) { return n < 10 ? '0' + n : '' + n; }\n" +
            "    return d.getUTCFullYear() + '-' + pad(d.getUTCMonth() + 1) + '-' + pad(d.getUTCDate()) +\n" +
            "        'T' + pad(d.getUTCHours()) + ':' + pad(d.getUTCMinutes()) + ':' + pad(d.getUTCSeconds()) + 'Z';\n" +
            '}',
    },
    {
        method: 'isArray',
        owner: 'Array',
        returnType: 'boolean',
        isConfirmed: true,
        esVersion: 5,
        isStatic: true,
        category: 'unavailable',
        ambiguousWithString: false,
        description: 'Array.isArray is not available in SFMC SSJS.',
        polyfill:
            '/**\n' +
            ' * Polyfill for Array.isArray (SFMC SSJS).\n' +
            ' * @param {*} value - the value to test\n' +
            ' * @returns {boolean} true when the value is an Array\n' +
            ' */\n' +
            'Array.isArray = Array.isArray || function (value) {\n' +
            "    return Object.prototype.toString.call(value) === '[object Array]';\n" +
            '};',
    },
    {
        method: 'of',
        owner: 'Array',
        returnType: 'array',
        isConfirmed: true,
        esVersion: 6,
        isStatic: true,
        category: 'unavailable',
        ambiguousWithString: false,
        description: 'Array.of is not available in SFMC SSJS.',
        polyfill:
            '/**\n' +
            ' * Polyfill for Array.of (SFMC SSJS).\n' +
            ' * @param {...*} [items] - elements to place in the new array\n' +
            ' * @returns {Array} a new array containing the arguments\n' +
            ' */\n' +
            'Array.of = Array.of || function () {\n' +
            '    var result = [];\n' +
            '    for (var i = 0; i < arguments.length; i++) {\n' +
            '        result.push(arguments[i]);\n' +
            '    }\n' +
            '    return result;\n' +
            '};',
    },
    {
        method: 'substr',
        owner: 'String.prototype',
        returnType: 'string',
        isConfirmed: true,
        esVersion: 3,
        isStatic: false,
        category: 'unavailable',
        ambiguousWithString: false,
        description:
            'String.prototype.substr is not available in SFMC SSJS (calling it throws). ' +
            'Use substring() or this polyfill that maps (start, length) onto substring().',
        polyfill:
            '/**\n' +
            ' * Polyfill for String.prototype.substr (SFMC SSJS).\n' +
            ' * @param {number} start - index to start extracting from (negative counts from the end)\n' +
            ' * @param {number} [length] - number of characters to extract (default: to the end)\n' +
            ' * @returns {string} the extracted substring\n' +
            ' */\n' +
            'String.prototype.substr = String.prototype.substr || function (start, length) {\n' +
            '    var len = this.length;\n' +
            '    var from = start < 0 ? Math.max(len + start, 0) : Math.min(start, len);\n' +
            '    var to = length === undefined ? len : from + (length < 0 ? 0 : length);\n' +
            '    return this.substring(from, to);\n' +
            '};',
    },
];
